#!/bin/bash
# ================================================
# registry-reference.sh
# Docker Registry Complete Reference
# Author: Asim Raza
# Day 32 of DevOps Journey
# ================================================

echo "============================================"
echo "   DOCKER REGISTRY REFERENCE"
echo "   Author: Asim Raza - Day 32"
echo "============================================"

echo ""
echo "[ REGISTRY TYPES ]"
echo "  Docker Hub:  hub.docker.com (default)"
echo "  ECR:         ACCOUNT.dkr.ecr.REGION.amazonaws.com"
echo "  GCR:         REGION-docker.pkg.dev"
echo "  ACR:         REGISTRY.azurecr.io"
echo "  GitHub:      ghcr.io/USERNAME/IMAGE"
echo "  Self-hosted: your.registry.com:5000"

echo ""
echo "[ IMAGE NAMING FORMAT ]"
echo "  Official:    nginx:alpine"
echo "  Docker Hub:  USERNAME/IMAGE:TAG"
echo "  ECR:         ACCOUNT.dkr.ecr.REGION.amazonaws.com/IMAGE:TAG"
echo "  Local:       localhost:5000/IMAGE:TAG"
echo "  Custom host: registry.company.com/IMAGE:TAG"

echo ""
echo "[ CORE COMMANDS ]"
echo "  docker login [REGISTRY]                = authenticate"
echo "  docker login --password-stdin           = secure login"
echo "  docker logout [REGISTRY]               = remove credentials"
echo "  docker pull IMAGE:TAG                  = download image"
echo "  docker push IMAGE:TAG                  = upload image"
echo "  docker push IMAGE --all-tags           = push all tags"
echo "  docker tag SOURCE TARGET               = add tag"

echo ""
echo "[ LOGIN EXAMPLES ]"
echo "  # Docker Hub:"
echo "  docker login"
echo ""
echo "  # Docker Hub with token:"
echo "  echo TOKEN | docker login --username USER --password-stdin"
echo ""
echo "  # ECR:"
echo "  aws ecr get-login-password --region REGION | \\"
echo "  docker login --username AWS --password-stdin REGISTRY"
echo ""
echo "  # GitHub Container Registry:"
echo "  echo TOKEN | docker login ghcr.io --username USER --password-stdin"
echo ""
echo "  # Self-hosted:"
echo "  docker login localhost:5000"

echo ""
echo "[ TAGGING STRATEGY ]"
echo "  Semantic versioning (recommended):"
echo "  myapp:1.0.0     = exact version (use in production)"
echo "  myapp:1.0       = minor version"
echo "  myapp:latest    = most recent (AVOID in production)"
echo ""
echo "  Git-based (fully reproducible):"
echo "  myapp:abc1234   = git commit SHA"
echo "  myapp:main-001  = branch + build number"
echo ""
echo "  Environment-based:"
echo "  myapp:staging   = staging deployment"
echo "  myapp:prod      = production deployment"

echo ""
echo "[ DOCKER HUB WORKFLOW ]"
echo "  1. docker login"
echo "  2. docker build -t USERNAME/app:v1.0 ."
echo "  3. docker push USERNAME/app:v1.0"
echo "  4. docker push USERNAME/app:latest"
echo "  On another machine:"
echo "  5. docker pull USERNAME/app:v1.0"
echo "  6. docker run USERNAME/app:v1.0"

echo ""
echo "[ ECR WORKFLOW ]"
echo "  1. aws ecr create-repository --repository-name app"
echo "  2. aws ecr get-login-password | docker login ..."
echo "  3. docker tag app:v1.0 ACCOUNT.dkr.ecr.REGION.amazonaws.com/app:v1.0"
echo "  4. docker push ACCOUNT.dkr.ecr.REGION.amazonaws.com/app:v1.0"
echo "  (Configure AWS CLI in Phase 6)"

echo ""
echo "[ SELF-HOSTED REGISTRY ]"
echo "  # Start registry:"
echo "  docker run -d -p 5000:5000 \\"
echo "    -v registry-data:/var/lib/registry \\"
echo "    registry:2"
echo ""
echo "  # Push to local registry:"
echo "  docker tag myapp:v1.0 localhost:5000/myapp:v1.0"
echo "  docker push localhost:5000/myapp:v1.0"
echo ""
echo "  # Registry API:"
echo "  curl localhost:5000/v2/_catalog       (list repos)"
echo "  curl localhost:5000/v2/app/tags/list  (list tags)"

echo ""
echo "[ SECURITY BEST PRACTICES ]"
echo "  ✅ Use access tokens NOT passwords"
echo "  ✅ Rotate tokens regularly"
echo "  ✅ Use specific version tags in production"
echo "  ✅ Enable image scanning (ECR has this)"
echo "  ✅ Use lifecycle policies to clean old images"
echo "  ✅ Private repos for internal images"
echo "  ✅ Use --password-stdin not -p flag"
echo "  ❌ Never use :latest in production"
echo "  ❌ Never store credentials in code"

echo ""
echo "[ CURRENT LOCAL IMAGES ]"
docker images | head -15

echo ""
echo "============================================"
echo "   REFERENCE COMPLETE"
echo "============================================"
