#!/bin/bash
# ================================================
# essential-plugins.sh
# Jenkins Essential Plugins Reference
# Author: Asim Raza - Day 46
# ================================================

echo "============================================"
echo "   JENKINS ESSENTIAL PLUGINS"
echo "============================================"

echo ""
echo "[ PIPELINE PLUGINS ]"
echo ""
echo "  Pipeline"
echo "    What: Core declarative pipeline support"
echo "    Enables: Jenkinsfile with stages/steps"
echo "    Required: YES (always)"
echo ""
echo "  Pipeline: Stage View"
echo "    What: Visual pipeline stage display"
echo "    Shows: which stage is running/failed"
echo "    Required: YES (debugging)"
echo ""
echo "  Pipeline Graph View"
echo "    What: Modern pipeline graph"
echo "    Better than: Stage View"
echo "    Required: Recommended"
echo ""
echo "  Blue Ocean"
echo "    What: Modern Jenkins UI"
echo "    Features: Better visualization, logs"
echo "    Access at: /blue"

echo ""
echo "[ SOURCE CONTROL PLUGINS ]"
echo ""
echo "  Git"
echo "    What: Git integration"
echo "    Enables: Clone, checkout, poll"
echo "    Required: YES (always)"
echo ""
echo "  GitHub Integration"
echo "    What: GitHub webhooks and API"
echo "    Enables: Trigger on push/PR"
echo "    Required: If using GitHub"
echo ""
echo "  GitHub Branch Source"
echo "    What: Scan GitHub orgs/repos"
echo "    Enables: Multi-branch pipelines from GitHub"

echo ""
echo "[ BUILD TOOL PLUGINS ]"
echo ""
echo "  Docker Pipeline"
echo "    What: Docker in Jenkinsfile"
echo "    Enables: docker.build(), docker.push()"
echo "    Required: If building Docker images"
echo ""
echo "  Maven Integration"
echo "    What: Maven build tool"
echo "    Enables: mvn commands in pipeline"
echo "    Required: For Java/Maven projects"
echo ""
echo "  NodeJS"
echo "    What: Node.js tool management"
echo "    Enables: npm commands in pipeline"
echo "    Required: For Node.js projects"
echo ""
echo "  Python"
echo "    What: Python tool management"
echo "    Enables: pip, pytest in pipeline"

echo ""
echo "[ QUALITY AND SECURITY PLUGINS ]"
echo ""
echo "  JUnit"
echo "    What: Test result publishing"
echo "    Enables: junit 'results.xml'"
echo "    Shows: test results in UI"
echo "    Required: YES (for test reporting)"
echo ""
echo "  Cobertura / JaCoCo"
echo "    What: Code coverage reporting"
echo "    Enables: Coverage trend graphs"
echo ""
echo "  OWASP Dependency-Check"
echo "    What: Vulnerability scanning"
echo "    Enables: CVE checks on dependencies"
echo ""
echo "  SonarQube Scanner"
echo "    What: Code quality analysis"
echo "    Enables: sonarqube { ... } in pipeline"

echo ""
echo "[ CREDENTIALS AND SECURITY PLUGINS ]"
echo ""
echo "  Credentials"
echo "    What: Secure credential store"
echo "    Enables: withCredentials { ... }"
echo "    Required: YES (always)"
echo ""
echo "  Credentials Binding"
echo "    What: Use credentials in shell"
echo "    Enables: env vars from credentials"
echo "    Required: YES (always)"
echo ""
echo "  SSH Agent"
echo "    What: SSH key injection"
echo "    Enables: sshagent(['key-id']) { ... }"

echo ""
echo "[ NOTIFICATION PLUGINS ]"
echo ""
echo "  Slack Notification"
echo "    What: Slack alerts"
echo "    Enables: slackSend(...)"
echo "    Configured: via Slack app token"
echo ""
echo "  Email Extension"
echo "    What: Rich email notifications"
echo "    Enables: emailext body: '...'"
echo ""
echo "  Build Name Setter"
echo "    What: Custom build names"
echo "    Enables: currentBuild.displayName"

echo ""
echo "[ UTILITY PLUGINS ]"
echo ""
echo "  Timestamper"
echo "    What: Timestamps in build logs"
echo "    Configure: options { timestamps() }"
echo "    Required: Recommended"
echo ""
echo "  AnsiColor"
echo "    What: Color in build logs"
echo "    Configure: options { ansiColor('xterm') }"
echo "    Makes logs much more readable"
echo ""
echo "  Build Timeout"
echo "    What: Kill long-running builds"
echo "    Configure: options { timeout(time: 30, unit: 'MINUTES') }"
echo ""
echo "  Workspace Cleanup"
echo "    What: Clean workspace before build"
echo "    Configure: options { cleanWs() }"
echo "    Prevents stale file issues"
echo ""
echo "  Parameter Binding"
echo "    What: Build parameters"
echo "    Enables: parameters { string(...) }"

echo ""
echo "[ HOW TO INSTALL PLUGINS ]"
echo ""
echo "  Method 1: UI (easy)"
echo "  Manage Jenkins → Plugins → Available"
echo "  Search, check boxes, Install"
echo ""
echo "  Method 2: Jenkins CLI"
echo "  java -jar jenkins-cli.jar install-plugin PLUGIN_ID"
echo ""
echo "  Method 3: At startup (best for Docker)"
echo "  In Dockerfile:"
echo "  FROM jenkins/jenkins:lts-jdk17"
echo "  RUN jenkins-plugin-cli --plugins \\"
echo "    pipeline-model-definition:latest \\"
echo "    git:latest \\"
echo "    docker-pipeline:latest"

echo ""
echo "============================================"
echo "   PLUGINS REFERENCE COMPLETE"
echo "============================================"
