#!/bin/bash
# ================================================
# security-config.sh
# Jenkins Security Configuration Reference
# Author: Asim Raza - Day 46
# ================================================

echo "============================================"
echo "   JENKINS SECURITY CONFIGURATION"
echo "============================================"

echo ""
echo "[ CRITICAL SECURITY SETTINGS ]"
echo ""
echo "  1. Enable Security"
echo "  Manage Jenkins → Security → Enable Security"
echo "  Security Realm: Jenkins own user database"
echo "  Authorization: Project-based Matrix"
echo ""
echo "  2. CSRF Protection"
echo "  Manage Jenkins → Security"
echo "  ☑ Prevent Cross Site Request Forgery"
echo "  This is ON by default in modern Jenkins"
echo ""
echo "  3. Agent → Controller Security"
echo "  Manage Jenkins → Security"
echo "  ☑ Enable Agent → Master Access Control"
echo ""
echo "  4. Script Approval"
echo "  When Groovy scripts run in Sandbox mode"
echo "  Unsafe operations need approval"
echo "  Manage Jenkins → In-process Script Approval"

echo ""
echo "[ CREDENTIALS BEST PRACTICES ]"
echo ""
echo "  NEVER in Jenkinsfile:"
echo "  ❌ def password = 'mysecret'"
echo "  ❌ env.DB_PASS = 'password'"
echo "  ❌ sh 'curl -u user:password ...'"
echo ""
echo "  ALWAYS use credentials store:"
echo "  ✅ withCredentials([string("
echo "    credentialsId: 'my-secret',"
echo "    variable: 'MY_SECRET')]) {"
echo "    sh 'curl -H \"Auth: \$MY_SECRET\" ...'"
echo "  }"
echo ""
echo "  Credential scopes:"
echo "  System: Only Jenkins itself"
echo "  Global: All jobs (most common)"
echo "  Folder: Jobs within specific folder"

echo ""
echo "[ PRODUCTION SECURITY CHECKLIST ]"
echo ""
echo "  ✅ Run behind HTTPS (nginx/Apache reverse proxy)"
echo "  ✅ Not exposed to public internet directly"
echo "  ✅ Strong admin password"
echo "  ✅ CSRF protection enabled"
echo "  ✅ Security realm enabled (not No Security)"
echo "  ✅ Regular plugin updates"
echo "  ✅ Jenkins itself updated"
echo "  ✅ Build logs don't contain secrets"
echo "  ✅ Docker socket mount reviewed"
echo "  ✅ Agent communication encrypted"
echo "  ✅ Backup jenkins_home regularly"
echo "  ✅ Audit log enabled"

echo ""
echo "[ JENKINS BEHIND NGINX (production) ]"
echo ""
echo "  /etc/nginx/sites-available/jenkins:"
echo "  server {"
echo "    listen 443 ssl;"
echo "    server_name jenkins.yourcompany.com;"
echo ""
echo "    location / {"
echo "      proxy_pass http://localhost:8080;"
echo "      proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "      proxy_set_header X-Forwarded-Proto https;"
echo "      proxy_set_header Host \$host;"
echo "    }"
echo "  }"
echo ""
echo "  In Jenkins: set Jenkins URL to:"
echo "  https://jenkins.yourcompany.com/"

echo ""
echo "[ BACKUP AND RESTORE ]"
echo ""
echo "  Backup Jenkins home (Docker volume):"
echo "  docker run --rm \\"
echo "    -v jenkins-data:/data \\"
echo "    -v \$(pwd):/backup \\"
echo "    ubuntu \\"
echo "    tar czf /backup/jenkins-backup-\$(date +%Y%m%d).tar.gz /data"
echo ""
echo "  Restore:"
echo "  docker run --rm \\"
echo "    -v jenkins-data:/data \\"
echo "    -v \$(pwd):/backup \\"
echo "    ubuntu \\"
echo "    tar xzf /backup/jenkins-backup-DATE.tar.gz -C /"
echo ""
echo "  What gets backed up:"
echo "  - All job configurations"
echo "  - Build history"
echo "  - Plugins"
echo "  - Credentials (encrypted)"
echo "  - User accounts"
echo "  - System configuration"

echo ""
echo "============================================"
echo "   SECURITY REFERENCE COMPLETE"
echo "============================================"
