#!/bin/bash
# ================================================
# setup-jenkins.sh
# Jenkins Installation and Initial Setup Guide
# Author: Asim Raza - Day 46
# ================================================

echo "============================================"
echo "   JENKINS SETUP - Day 46"
echo "   Author: Asim Raza"
echo "============================================"

echo ""
echo "[ STEP 1: Start Jenkins ]"
echo ""
echo "  cd ~/DevOps-journey/05-cicd/practices/day46-practice/jenkins-config"
echo "  docker compose up -d"
echo ""
echo "  This starts Jenkins on: http://localhost:8090"
echo "  First start: ~60 seconds to initialize"

echo ""
echo "[ STEP 2: Get Initial Admin Password ]"
echo ""
echo "  Method 1 (from container logs):"
echo "  docker logs jenkins-day46 2>&1 | grep -A 5 'initial admin password'"
echo ""
echo "  Method 2 (from file):"
echo "  docker exec jenkins-day46 cat /var/jenkins_home/secrets/initialAdminPassword"
echo ""
echo "  This password is required for first login"
echo "  Jenkins generates it on first run"
echo "  One-time use: changes after initial setup"

echo ""
echo "[ STEP 3: Initial Setup Wizard ]"
echo ""
echo "  1. Open: http://localhost:8090"
echo "  2. Enter initial admin password"
echo "  3. Choose: 'Install suggested plugins'"
echo "     (installs ~15 essential plugins)"
echo "  4. Wait: ~3-5 minutes for plugin install"
echo "  5. Create admin user:"
echo "     Username: admin"
echo "     Password: DevOps2026!"
echo "     Full name: Asim Raza"
echo "     Email: asim@devops.local"
echo "  6. Jenkins URL: http://localhost:8090"
echo "  7. Click: 'Start using Jenkins'"

echo ""
echo "[ STEP 4: Essential Plugins to Install ]"
echo ""
echo "  After initial setup, install via:"
echo "  Manage Jenkins → Plugins → Available plugins"
echo ""
echo "  REQUIRED plugins:"
echo "  - Pipeline (usually pre-installed)"
echo "  - Git (usually pre-installed)"
echo "  - Docker Pipeline"
echo "  - Blue Ocean (modern UI)"
echo "  - GitHub Integration"
echo "  - Credentials Binding"
echo "  - AnsiColor"
echo "  - Build Timeout"
echo "  - Timestamper"
echo "  - Workspace Cleanup"
echo "  - Pipeline Graph View"

echo ""
echo "[ STEP 5: Configure Global Tools ]"
echo ""
echo "  Manage Jenkins → Tools:"
echo ""
echo "  JDK:"
echo "  Name: JDK-17"
echo "  JAVA_HOME: /opt/java/openjdk"
echo ""
echo "  Git:"
echo "  Name: Default"
echo "  Path: git"
echo ""
echo "  Maven (if needed):"
echo "  Name: Maven-3"
echo "  Install automatically: ✅"
echo "  Version: 3.9.x"
echo ""
echo "  Docker:"
echo "  Name: Docker"
echo "  Path: docker"

echo ""
echo "[ STEP 6: Configure Credentials ]"
echo ""
echo "  Manage Jenkins → Credentials → Global → Add:"
echo ""
echo "  GitHub credentials:"
echo "  Kind: Username with password"
echo "  Username: Muhammad-Asim-raza"
echo "  Password: [GitHub Personal Access Token]"
echo "  ID: github-credentials"
echo "  Description: GitHub PAT"
echo ""
echo "  Docker Hub credentials:"
echo "  Kind: Username with password"
echo "  Username: your-dockerhub-username"
echo "  Password: [Docker Hub Access Token]"
echo "  ID: dockerhub-credentials"
echo ""
echo "  SSH key:"
echo "  Kind: SSH Username with private key"
echo "  Username: deploy"
echo "  Private Key: [paste SSH private key]"
echo "  ID: deploy-ssh-key"
echo ""
echo "  Secret text:"
echo "  Kind: Secret text"
echo "  Secret: [value]"
echo "  ID: my-secret"

echo ""
echo "[ STEP 7: Security Configuration ]"
echo ""
echo "  Manage Jenkins → Security:"
echo "  Authorization: Matrix-based security"
echo "  Add admin user: full permissions"
echo "  Other users: build/read only"
echo ""
echo "  Security checklist:"
echo "  ✅ Enable CSRF protection"
echo "  ✅ Enable security realm"
echo "  ✅ Disable agent-to-master security"
echo "     (only for trusted internal agents)"
echo "  ✅ Use HTTPS in production"
echo "  ✅ Configure backup"

echo ""
echo "[ JENKINS DIRECTORY STRUCTURE ]"
echo ""
echo "  /var/jenkins_home/"
echo "  ├── jobs/              ← All your pipelines"
echo "  │   ├── my-pipeline/"
echo "  │   │   ├── config.xml ← Job configuration"
echo "  │   │   └── builds/"   ← Build history"
echo "  ├── plugins/           ← Installed plugins"
echo "  ├── secrets/           ← Credentials"
echo "  │   └── initialAdminPassword"
echo "  ├── users/             ← User accounts"
echo "  ├── workspace/         ← Active workspaces"
echo "  │   └── my-pipeline/   ← Job workspace"
echo "  ├── logs/              ← Jenkins logs"
echo "  └── config.xml         ← Global config"

echo ""
echo "============================================"
echo "   SETUP GUIDE COMPLETE"
echo "============================================"
