# ================================================
# Blue Deployment (current production)
# Author: Asim Raza - Day 50
# ================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
  labels:
    app: demo
    color: blue
    version: "1.0.0"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo
      color: blue
  template:
    metadata:
      labels:
        app: demo
        color: blue
        version: "1.0.0"
    spec:
      containers:
        - name: app
          image: nginx:1.24-alpine
          # v1.0.0 = nginx:1.24
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
