#!/bin/bash
# ================================================
# aws-fundamentals-reference.sh
# AWS Fundamentals Complete Reference
# Author: Asim Raza - Day 53
# ================================================

echo "============================================"
echo "   AWS FUNDAMENTALS REFERENCE"
echo "   Author: Asim Raza - Day 53"
echo "============================================"

echo ""
echo "[ CLOUD COMPUTING MODELS ]"
echo "  IaaS: you manage OS + apps (EC2, S3)"
echo "  PaaS: you manage apps only (RDS, Lambda)"
echo "  SaaS: you use the service (Gmail, Slack)"

echo ""
echo "[ AWS GLOBAL INFRASTRUCTURE ]"
echo "  Regions:           33+ geographic areas"
echo "  Availability Zones: 3-6 per region"
echo "  Edge Locations:    400+ for CloudFront CDN"
echo ""
echo "  Region naming: us-east-1, eu-west-1"
echo "  AZ naming:     us-east-1a, us-east-1b"
echo ""
echo "  For High Availability: deploy to 2+ AZs"

echo ""
echo "[ SHARED RESPONSIBILITY ]"
echo "  AWS: physical hardware, network, hypervisor"
echo "  You: data, IAM, OS patches, app security"

echo ""
echo "[ CORE SERVICES — DEVOPS FOCUS ]"
echo "  Compute:   EC2, ECS, EKS, Lambda, Fargate"
echo "  Storage:   S3, EBS, EFS, ECR"
echo "  Network:   VPC, ALB, Route53, CloudFront"
echo "  Database:  RDS, Aurora, DynamoDB, ElastiCache"
echo "  Security:  IAM, KMS, Secrets Manager, WAF"
echo "  Monitor:   CloudWatch, CloudTrail, X-Ray"
echo "  CI/CD:     CodePipeline, CodeBuild, CodeDeploy"

echo ""
echo "[ PRICING MODEL ]"
echo "  Pay as you go (no upfront)"
echo "  On-Demand: most flexible, most expensive"
echo "  Reserved 1-3yr: 30-72% discount"
echo "  Spot: up to 90% off, interruptible"
echo "  Savings Plans: flexible commitment"

echo ""
echo "[ AWS CLI ESSENTIALS ]"
echo "  Install: curl from awscli.amazonaws.com"
echo "  Config:  aws configure"
echo "  Files:   ~/.aws/credentials, ~/.aws/config"
echo ""
echo "  Verify:  aws sts get-caller-identity"
echo "  Regions: aws ec2 describe-regions"
echo "  Buckets: aws s3 ls"
echo ""
echo "  Flags:"
echo "  --region REGION   override region"
echo "  --profile NAME    use named profile"
echo "  --output FORMAT   json|text|table"
echo "  --query JMESPATH  filter results"
echo "  --dry-run         test without executing"

echo ""
echo "[ PHASE 6 PLAN ]"
echo "  Day 53: Fundamentals (TODAY)"
echo "  Day 54: IAM"
echo "  Day 55: VPC"
echo "  Day 56: EC2"
echo "  Day 57: S3"
echo "  Day 58: RDS"
echo "  Day 59: ECS"
echo "  Day 60: EKS"
echo "  Day 61: CloudFormation"
echo "  Day 62: Lambda"
echo "  Day 63: API Gateway"
echo "  Day 64: CloudWatch"
echo "  Day 65: Route53"
echo "  Day 66: Load Balancers"
echo "  Day 67: Auto Scaling"
echo "  Day 68: AWS Security"
echo "  Day 69: Cost Optimization"
echo "  Day 70: AWS Phase Project"

echo ""
echo "[ AWS CLI STATUS ]"
aws --version 2>/dev/null || echo "  AWS CLI: install pending"
aws sts get-caller-identity 2>/dev/null || \
    echo "  Credentials: configure with 'aws configure'"

echo ""
echo "============================================"
echo "   REFERENCE COMPLETE"
echo "============================================"
