#!/bin/bash
# ================================================
# cicd-reference.sh
# Complete CI/CD Reference - Day 39
# Author: Asim Raza
# ================================================

echo "============================================"
echo "   CI/CD COMPLETE REFERENCE"
echo "   Author: Asim Raza - Day 39"
echo "============================================"

echo ""
echo "[ WHAT IS CI/CD ]"
echo "  Continuous Integration:"
echo "    Merge code often + automated tests"
echo "    Catch bugs early (before they compound)"
echo ""
echo "  Continuous Delivery:"
echo "    Always deployable + human approves prod"
echo ""
echo "  Continuous Deployment:"
echo "    Fully automated + auto-deploys to prod"

echo ""
echo "[ CI/CD PIPELINE STAGES ]"
echo "  1. Source    → git push triggers pipeline"
echo "  2. Build     → compile, install deps"
echo "  3. Test      → unit, integration tests"
echo "  4. Security  → SAST, dependency scan"
echo "  5. Image     → docker build + push"
echo "  6. Staging   → deploy + smoke tests"
echo "  7. Production→ deploy (auto or approved)"
echo "  8. Notify    → Slack, email, PagerDuty"

echo ""
echo "[ CI/CD TOOLS WE STUDY ]"
echo "  GitHub Actions  → Days 40-45"
echo "  Jenkins         → Days 46-47"
echo "  GitLab CI       → Day 48"
echo "  ArgoCD (GitOps) → Day 49"

echo ""
echo "[ KEY METRICS (DORA) ]"
echo "  Deployment Frequency   → how often"
echo "  Lead Time for Changes  → commit → prod"
echo "  Change Failure Rate    → % broken deploys"
echo "  Time to Restore        → recovery time"
echo ""
echo "  Elite: daily deploys, <1hr lead time"
echo "  Low:   monthly deploys, months lead time"

echo ""
echo "[ DEPLOYMENT STRATEGIES ]"
echo "  Rolling     → update batch by batch"
echo "  Blue-Green  → switch traffic instantly"
echo "  Canary      → 5% → 100% gradually"
echo "  Feature Flag→ deploy off, enable later"

echo ""
echo "[ WHAT CI/CD REPLACES ]"
echo "  Manual SSH into server"
echo "  Manual git pull"
echo "  Manual restart"
echo "  Manual testing"
echo "  Deployment fear"
echo "  2am emergencies (mostly)"

echo ""
echo "[ CI/CD FILE LOCATIONS ]"
echo "  GitHub Actions:  .github/workflows/*.yml"
echo "  GitLab CI:       .gitlab-ci.yml"
echo "  Jenkins:         Jenkinsfile"
echo "  CircleCI:        .circleci/config.yml"
echo "  Travis CI:       .travis.yml"

echo ""
echo "[ PHASE 5 PLAN ]"
echo "  Day 39: What is CI/CD (TODAY)"
echo "  Day 40: GitHub Actions fundamentals"
echo "  Day 41: Workflows jobs steps triggers"
echo "  Day 42: Secrets and env management"
echo "  Day 43: Build and test automation"
echo "  Day 44: Docker in GitHub Actions"
echo "  Day 45: Deploy automation"
echo "  Day 46: Jenkins setup"
echo "  Day 47: Jenkins pipelines"
echo "  Day 48: GitLab CI"
echo "  Day 49: ArgoCD GitOps"
echo "  Day 50: Deployment strategies"
echo "  Day 51: CI/CD security scanning"
echo "  Day 52: CI/CD PHASE PROJECT"

echo ""
echo "============================================"
echo "   REFERENCE COMPLETE"
echo "============================================"
