#!/bin/bash
# ================================================
# 01-iam-cli-reference.sh
# AWS IAM CLI Commands Reference
# Author: Asim Raza - Day 54
# ================================================

echo "============================================"
echo "   AWS IAM CLI REFERENCE"
echo "   Author: Asim Raza - Day 54"
echo "============================================"

echo ""
echo "[ USERS ]"
echo ""
echo "  # List all IAM users:"
echo "  aws iam list-users --output table"
echo ""
echo "  # Create a user:"
echo "  aws iam create-user --user-name devops-engineer"
echo ""
echo "  # Get user details:"
echo "  aws iam get-user --user-name devops-engineer"
echo ""
echo "  # Delete user:"
echo "  aws iam delete-user --user-name devops-engineer"
echo ""
echo "  # Create access key:"
echo "  aws iam create-access-key --user-name devops-engineer"
echo ""
echo "  # List access keys:"
echo "  aws iam list-access-keys --user-name devops-engineer"
echo ""
echo "  # Deactivate access key:"
echo "  aws iam update-access-key \\"
echo "    --user-name devops-engineer \\"
echo "    --access-key-id AKIAIOSFODNN7EXAMPLE \\"
echo "    --status Inactive"
echo ""
echo "  # Delete access key:"
echo "  aws iam delete-access-key \\"
echo "    --user-name devops-engineer \\"
echo "    --access-key-id AKIAIOSFODNN7EXAMPLE"

echo ""
echo "[ GROUPS ]"
echo ""
echo "  # List groups:"
echo "  aws iam list-groups"
echo ""
echo "  # Create group:"
echo "  aws iam create-group --group-name DevOpsEngineers"
echo ""
echo "  # Add user to group:"
echo "  aws iam add-user-to-group \\"
echo "    --user-name devops-engineer \\"
echo "    --group-name DevOpsEngineers"
echo ""
echo "  # List users in group:"
echo "  aws iam get-group --group-name DevOpsEngineers"
echo ""
echo "  # Remove user from group:"
echo "  aws iam remove-user-from-group \\"
echo "    --user-name devops-engineer \\"
echo "    --group-name DevOpsEngineers"

echo ""
echo "[ ROLES ]"
echo ""
echo "  # List roles:"
echo "  aws iam list-roles --output table"
echo ""
echo "  # Create role with trust policy:"
echo "  aws iam create-role \\"
echo "    --role-name MyEC2Role \\"
echo "    --assume-role-policy-document file://trust-policy.json"
echo ""
echo "  # Get role:"
echo "  aws iam get-role --role-name MyEC2Role"
echo ""
echo "  # Delete role:"
echo "  aws iam delete-role --role-name MyEC2Role"
echo ""
echo "  # Assume a role (get temporary credentials):"
echo "  aws sts assume-role \\"
echo "    --role-arn arn:aws:iam::123456789012:role/MyRole \\"
echo "    --role-session-name MySession"

echo ""
echo "[ POLICIES ]"
echo ""
echo "  # List AWS managed policies:"
echo "  aws iam list-policies \\"
echo "    --scope AWS \\"
echo "    --output table | head -30"
echo ""
echo "  # Create customer managed policy:"
echo "  aws iam create-policy \\"
echo "    --policy-name MyS3Policy \\"
echo "    --policy-document file://policy.json"
echo ""
echo "  # Get policy:"
echo "  aws iam get-policy \\"
echo "    --policy-arn arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
echo ""
echo "  # Attach policy to user:"
echo "  aws iam attach-user-policy \\"
echo "    --user-name devops-engineer \\"
echo "    --policy-arn arn:aws:iam::aws:policy/ReadOnlyAccess"
echo ""
echo "  # Attach policy to role:"
echo "  aws iam attach-role-policy \\"
echo "    --role-name MyEC2Role \\"
echo "    --policy-arn arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
echo ""
echo "  # List policies attached to role:"
echo "  aws iam list-attached-role-policies \\"
echo "    --role-name MyEC2Role"
echo ""
echo "  # Detach policy from role:"
echo "  aws iam detach-role-policy \\"
echo "    --role-name MyEC2Role \\"
echo "    --policy-arn arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"

echo ""
echo "[ INSTANCE PROFILES (EC2 Roles) ]"
echo ""
echo "  # Create instance profile:"
echo "  aws iam create-instance-profile \\"
echo "    --instance-profile-name MyEC2Profile"
echo ""
echo "  # Add role to instance profile:"
echo "  aws iam add-role-to-instance-profile \\"
echo "    --instance-profile-name MyEC2Profile \\"
echo "    --role-name MyEC2Role"
echo ""
echo "  # Attach to EC2 instance:"
echo "  aws ec2 associate-iam-instance-profile \\"
echo "    --instance-id i-0abc123 \\"
echo "    --iam-instance-profile Name=MyEC2Profile"

echo ""
echo "[ IAM CREDENTIAL REPORT ]"
echo ""
echo "  # Generate credential report:"
echo "  aws iam generate-credential-report"
echo ""
echo "  # Download report:"
echo "  aws iam get-credential-report \\"
echo "    --query 'Content' --output text | base64 -d"
echo ""
echo "  Report contains:"
echo "  - All users"
echo "  - Password last used"
echo "  - Access key last used"
echo "  - MFA enabled"
echo "  Use for: security audits, compliance"

echo ""
echo "[ CURRENT ACCOUNT INFO ]"
if command -v aws &>/dev/null; then
    echo ""
    aws sts get-caller-identity 2>/dev/null || \
        echo "  (Configure credentials: aws configure)"
fi

echo ""
echo "============================================"
echo "   IAM CLI REFERENCE COMPLETE"
echo "============================================"
