#!/bin/bash
# ================================================
# 03-iam-best-practices.sh
# IAM Best Practices Reference
# Author: Asim Raza - Day 54
# ================================================

echo "============================================"
echo "   IAM BEST PRACTICES"
echo "   Production security patterns"
echo "============================================"

echo ""
echo "[ BEST PRACTICE 1: Lock down root account ]"
echo ""
echo "  ✅ Enable MFA on root"
echo "  ✅ Delete root access keys"
echo "  ✅ Never use root for daily operations"
echo "  ✅ Create billing alert from root, then never again"
echo "  ✅ Use root only for: closing account, changing email,"
echo "     restoring IAM permissions if locked out"

echo ""
echo "[ BEST PRACTICE 2: Principle of Least Privilege ]"
echo ""
echo "  Grant ONLY the permissions required"
echo "  Nothing more"
echo ""
echo "  WRONG:"
echo "  Effect: Allow"
echo "  Action: '*'"
echo "  Resource: '*'"
echo "  (Full admin = if compromised → everything lost)"
echo ""
echo "  RIGHT:"
echo "  Effect: Allow"
echo "  Action: ['s3:GetObject', 's3:PutObject']"
echo "  Resource: 'arn:aws:s3:::my-app-bucket/*'"
echo "  (Only what this specific service needs)"
echo ""
echo "  How to determine least privilege:"
echo "  1. Use IAM Access Advisor (shows last used)"
echo "  2. Start with no permissions"
echo "  3. Add what app needs, test, repeat"
echo "  4. Use AWS IAM Policy Simulator to test"

echo ""
echo "[ BEST PRACTICE 3: Use Roles Not Users for Services ]"
echo ""
echo "  WRONG: Give EC2 an IAM User access key"
echo "  Access key stored in /etc/environment"
echo "  Or worse: hardcoded in app.py"
echo "  If EC2 is compromised: key stolen"
echo "  Key never auto-expires"
echo ""
echo "  RIGHT: Give EC2 an IAM Role (instance profile)"
echo "  No access key stored anywhere"
echo "  Credentials auto-rotate every hour"
echo "  If EC2 compromised: attacker gets 1hr creds"
echo "  After 1 hour: creds expire automatically"
echo ""
echo "  Same principle for:"
echo "  Lambda → Lambda execution role"
echo "  ECS → Task role"
echo "  GitHub Actions → OIDC role"
echo "  Cross-account → AssumeRole"

echo ""
echo "[ BEST PRACTICE 4: Use Groups Not Direct Policies ]"
echo ""
echo "  WRONG: Attach policies directly to users"
echo "  10 developers → 10 separate policy attachments"
echo "  Hard to audit"
echo "  Easy to forget when developer leaves"
echo ""
echo "  RIGHT: Groups → Policies → Users join groups"
echo "  Developers group → S3 read, ECR pull"
echo "  DevOps group → Full EC2, ECS, S3"
echo "  NewDev starts → add to Developers group"
echo "  Dev leaves → remove from all groups"
echo "  Easy to audit: who is in which group"

echo ""
echo "[ BEST PRACTICE 5: Enable MFA for human users ]"
echo ""
echo "  Console access → REQUIRE MFA"
echo "  API/CLI access → strongly recommended"
echo ""
echo "  Enforce MFA with condition:"
echo "  'Condition': {"
echo "    'Bool': {"
echo "      'aws:MultiFactorAuthPresent': 'true'"
echo "    }"
echo "  }"
echo ""
echo "  AWS Config Rule: iam-user-mfa-enabled"
echo "  Flags all users without MFA"

echo ""
echo "[ BEST PRACTICE 6: Rotate Credentials ]"
echo ""
echo "  Access keys: rotate every 90 days MAX"
echo "  Passwords: enforce 90-day rotation via policy"
echo ""
echo "  Check key age:"
echo "  aws iam list-access-keys --user-name USER"
echo "  Look at CreateDate"
echo ""
echo "  Automate rotation:"
echo "  AWS Secrets Manager: auto-rotates RDS passwords"
echo "  OIDC: no keys to rotate (best!)"
echo ""
echo "  Audit unused keys:"
echo "  aws iam get-credential-report"
echo "  Keys unused >90 days → deactivate and investigate"

echo ""
echo "[ BEST PRACTICE 7: Use Tags for Access Control ]"
echo ""
echo "  Tag resources: Environment=production"
echo "  Policy condition: only access if tagged"
echo ""
echo "  Example: Developer can only delete dev resources"
echo "  Condition:"
echo "    StringEquals:"
echo "      aws:ResourceTag/Environment: development"
echo ""
echo "  This prevents developers from accidentally"
echo "  deleting production resources even with"
echo "  seemingly broad permissions"

echo ""
echo "[ BEST PRACTICE 8: Use Permission Boundaries ]"
echo ""
echo "  Permission Boundary = maximum allowed permissions"
echo "  Even if policy allows more, boundary caps it"
echo ""
echo "  Use case: delegate IAM to team leads"
echo "  Lead can create roles but not exceed boundary"
echo "  Prevents: privilege escalation attacks"

echo ""
echo "[ BEST PRACTICE 9: Enable CloudTrail ]"
echo ""
echo "  Every IAM action logged"
echo "  Who created/deleted/modified what"
echo "  When, from which IP"
echo ""
echo "  aws cloudtrail create-trail \\"
echo "    --name my-audit-trail \\"
echo "    --s3-bucket-name my-cloudtrail-bucket"
echo ""
echo "  Query IAM events:"
echo "  aws cloudtrail lookup-events \\"
echo "    --lookup-attributes \\"
echo "      AttributeKey=EventName,AttributeValue=DeleteBucket"

echo ""
echo "[ IAM SECURITY CHECKLIST ]"
echo ""
echo "  ✅ Root MFA enabled"
echo "  ✅ No root access keys"
echo "  ✅ All users in groups"
echo "  ✅ MFA for all human users"
echo "  ✅ Access keys < 90 days old"
echo "  ✅ Services use roles not user keys"
echo "  ✅ No wildcard * policies in production"
echo "  ✅ CloudTrail enabled"
echo "  ✅ Credential report reviewed monthly"
echo "  ✅ AWS Config IAM rules enabled"

echo ""
echo "============================================"
echo "   BEST PRACTICES COMPLETE"
echo "============================================"
