#!/bin/bash
# ================================================
# vpc-reference.sh
# VPC Complete Reference
# Author: Asim Raza - Day 55
# ================================================

echo "============================================"
echo "   AWS VPC COMPLETE REFERENCE"
echo "   Author: Asim Raza - Day 55"
echo "============================================"

echo ""
echo "[ VPC COMPONENTS ]"
echo "  VPC:             your isolated private network"
echo "  Subnet:          subdivision of VPC, in one AZ"
echo "  IGW:             connects VPC to internet"
echo "  NAT Gateway:     private → internet (outbound only)"
echo "  Route Table:     controls traffic routing"
echo "  Security Group:  instance-level, stateful, allow-only"
echo "  NACL:            subnet-level, stateless, allow+deny"
echo "  VPC Endpoint:    private access to AWS services"
echo "  VPC Peering:     connect two VPCs"
echo "  Flow Logs:       capture traffic metadata"

echo ""
echo "[ SUBNET TYPES ]"
echo "  Public subnet:   has route 0.0.0.0/0 → IGW"
echo "                   resources CAN have public IPs"
echo "                   use: ALB, NAT GW, Bastion"
echo ""
echo "  Private subnet:  no route to IGW"
echo "                   resources CANNOT be reached from internet"
echo "                   can reach internet via NAT GW"
echo "                   use: EC2 app servers, ECS, Lambda"
echo ""
echo "  DB subnet:       private + extra restricted NACL"
echo "                   only accessible from private subnet"
echo "                   use: RDS, ElastiCache"

echo ""
echo "[ SECURITY GROUPS vs NACLs ]"
echo "  SG:   instance-level, stateful, allow only"
echo "  NACL: subnet-level, stateless, allow + deny"
echo ""
echo "  For blocking specific IPs → use NACL"
echo "  For service-to-service control → use SG"
echo "  Production: use BOTH (defense in depth)"

echo ""
echo "[ CIDR QUICK REFERENCE ]"
echo "  /16 = 65,536 IPs (use for VPC)"
echo "  /24 = 256 IPs   (use for subnets)"
echo "  /28 = 16 IPs    (minimum subnet)"
echo "  /32 = 1 IP      (exact host)"
echo ""
echo "  Private ranges:"
echo "  10.0.0.0/8     (preferred for VPCs)"
echo "  172.16.0.0/12"
echo "  192.168.0.0/16"

echo ""
echo "[ KEY CLI COMMANDS ]"
echo "  aws ec2 describe-vpcs"
echo "  aws ec2 describe-subnets"
echo "  aws ec2 describe-internet-gateways"
echo "  aws ec2 describe-route-tables"
echo "  aws ec2 describe-security-groups"
echo "  aws ec2 describe-nat-gateways"
echo "  aws ec2 describe-network-acls"
echo "  aws ec2 create-vpc --cidr-block 10.0.0.0/16"
echo "  aws ec2 create-subnet --vpc-id vpc-xxx --cidr-block 10.0.1.0/24"

echo ""
echo "[ 3-TIER ARCHITECTURE IP PLAN ]"
echo "  VPC:           10.0.0.0/16"
echo "  Public AZ-a:   10.0.1.0/24   (ALB, NAT GW)"
echo "  Public AZ-b:   10.0.2.0/24   (ALB, NAT GW)"
echo "  Private AZ-a:  10.0.10.0/24  (EC2, ECS)"
echo "  Private AZ-b:  10.0.11.0/24  (EC2, ECS)"
echo "  Database AZ-a: 10.0.20.0/24  (RDS)"
echo "  Database AZ-b: 10.0.21.0/24  (RDS standby)"

echo ""
echo "[ TRAFFIC FLOW ]"
echo "  Internet → IGW → ALB (public subnet)"
echo "          → App EC2 (private subnet)"
echo "          → RDS (database subnet)"
echo ""
echo "  Private EC2 → NAT GW (public subnet)"
echo "             → IGW → Internet"
echo "             (updates, external APIs)"

echo ""
echo "============================================"
echo "   VPC REFERENCE COMPLETE"
echo "============================================"
