#!/bin/bash
# ================================================
# setup-github-secrets.sh
# Reference: How to set up GitHub Secrets
# Author: Asim Raza - Day 42
# ================================================

echo "============================================"
echo "   GITHUB SECRETS SETUP REFERENCE"
echo "   Author: Asim Raza - Day 42"
echo "============================================"

echo ""
echo "[ METHOD 1: GitHub CLI (gh) ]"
echo ""
echo "  Install: sudo apt install gh"
echo "  Login:   gh auth login"
echo ""
echo "  Set repository secret:"
echo "  gh secret set SECRET_NAME"
echo "  (prompts for value securely)"
echo ""
echo "  Set from file:"
echo "  gh secret set SECRET_NAME < secret.txt"
echo ""
echo "  Set from environment variable:"
echo "  echo \"\$MY_VALUE\" | gh secret set SECRET_NAME"
echo ""
echo "  List secrets:"
echo "  gh secret list"
echo ""
echo "  Delete secret:"
echo "  gh secret delete SECRET_NAME"

echo ""
echo "[ METHOD 2: GitHub Web UI ]"
echo ""
echo "  Repository secrets:"
echo "  Repo → Settings → Secrets → Actions"
echo "  → New repository secret"
echo "  Name: MY_SECRET"
echo "  Value: the-actual-secret-value"
echo ""
echo "  Environment secrets:"
echo "  Repo → Settings → Environments"
echo "  → Select environment"
echo "  → Add secret"

echo ""
echo "[ METHOD 3: GitHub API ]"
echo ""
echo "  curl -X PUT \\"
echo "    -H 'Authorization: token PAT' \\"
echo "    -H 'Accept: application/vnd.github+json' \\"
echo "    https://api.github.com/repos/OWNER/REPO/actions/secrets/NAME \\"
echo "    -d '{\"encrypted_value\": \"...\", \"key_id\": \"...\"}'"
echo ""
echo "  Note: Value must be encrypted with repo public key"
echo "  Use: gh secret set (handles encryption)"

echo ""
echo "[ SECRETS NAMING CONVENTIONS ]"
echo ""
echo "  Repository secrets (global):"
echo "  DOCKERHUB_USERNAME"
echo "  DOCKERHUB_TOKEN"
echo "  SONAR_TOKEN"
echo "  SLACK_WEBHOOK_URL"
echo ""
echo "  Environment secrets (per-env):"
echo "  DB_PASSWORD          (different per env)"
echo "  DB_CONNECTION_STRING (different per env)"
echo "  AWS_ROLE_ARN         (different per env)"
echo "  REDIS_URL            (different per env)"
echo ""
echo "  OIDC (no secrets needed!):"
echo "  AWS_ROLE_ARN: arn:aws:iam::123:role/github-role"
echo "  (IAM role trusts GitHub OIDC - no key needed)"

echo ""
echo "[ WHAT SHOULD BE A SECRET vs VARIABLE ]"
echo ""
echo "  SECRET (encrypted, masked in logs):"
echo "  ✅ Passwords"
echo "  ✅ API keys and tokens"
echo "  ✅ Connection strings with credentials"
echo "  ✅ SSH private keys"
echo "  ✅ Certificate private keys"
echo ""
echo "  VARIABLE (visible, not encrypted):"
echo "  ✅ Region names (us-east-1)"
echo "  ✅ Application names"
echo "  ✅ Non-sensitive URLs"
echo "  ✅ Feature flags"
echo "  ✅ Version numbers"
echo "  ✅ Timeout values"

echo ""
echo "[ GITHUB SECRETS USED IN DEVOPS JOURNEY ]"
echo ""
echo "  For Docker (Day 44):"
echo "  DOCKERHUB_USERNAME = your Docker Hub username"
echo "  DOCKERHUB_TOKEN = Docker Hub access token"
echo ""
echo "  For AWS (Phase 6):"
echo "  AWS_ACCOUNT_ID = your AWS account ID"
echo "  (OIDC replaces access keys)"
echo ""
echo "  For notifications:"
echo "  SLACK_WEBHOOK_URL = Slack incoming webhook"
echo ""
echo "  Built-in (no setup needed):"
echo "  GITHUB_TOKEN = automatic per-run token"

echo ""
echo "============================================"
echo "   SETUP REFERENCE COMPLETE"
echo "============================================"
