#!/bin/bash
# ================================================
# iam-reference.sh
# IAM Complete Reference
# Author: Asim Raza - Day 54
# ================================================

echo "============================================"
echo "   AWS IAM COMPLETE REFERENCE"
echo "   Author: Asim Raza - Day 54"
echo "============================================"

echo ""
echo "[ IAM COMPONENTS ]"
echo "  Root    = unlimited, use only for setup + billing"
echo "  User    = human identity with credentials"
echo "  Group   = users collection, attach policies once"
echo "  Role    = temporary identity for services"
echo "  Policy  = JSON permissions document"

echo ""
echo "[ POLICY ANATOMY ]"
echo "  Effect:   Allow | Deny"
echo "  Action:   service:ApiCall (e.g., s3:GetObject)"
echo "  Resource: ARN of specific resource"
echo "  Condition: optional extra restrictions"
echo ""
echo "  Default: DENY (must explicitly Allow)"
echo "  Explicit Deny: ALWAYS wins over Allow"

echo ""
echo "[ ARN FORMAT ]"
echo "  arn:aws:service:region:account:resource"
echo "  arn:aws:iam::123456789012:user/asim"
echo "  arn:aws:ec2:us-east-1:123456789012:instance/i-abc"
echo "  arn:aws:s3:::my-bucket (no region/account for S3)"

echo ""
echo "[ ROLES vs USERS FOR SERVICES ]"
echo "  User + access key: stored, never rotates, risky"
echo "  Role: auto-rotates every hour, no storage, safe"
echo ""
echo "  EC2: IAM instance profile (role)"
echo "  Lambda: execution role"
echo "  ECS: task role"
echo "  GitHub Actions: OIDC role (no keys at all!)"

echo ""
echo "[ GITHUB ACTIONS OIDC ]"
echo "  1. Create OIDC provider in IAM"
echo "     URL: token.actions.githubusercontent.com"
echo "  2. Create IAM role with OIDC trust policy"
echo "     Condition: sub=repo:OWNER/REPO:ref:refs/heads/main"
echo "  3. In workflow: permissions: id-token: write"
echo "  4. Use: aws-actions/configure-aws-credentials@v4"
echo "  Result: No AWS keys stored anywhere!"

echo ""
echo "[ SECURITY CHECKLIST ]"
echo "  ✅ Root MFA enabled"
echo "  ✅ No root access keys"
echo "  ✅ Users in groups (not direct policies)"
echo "  ✅ MFA for all human console users"
echo "  ✅ Access keys < 90 days old"
echo "  ✅ Services use roles not user keys"
echo "  ✅ No wildcard * Resource in policies"
echo "  ✅ CloudTrail enabled"
echo "  ✅ Least privilege enforced"

echo ""
echo "[ KEY CLI COMMANDS ]"
echo "  aws iam list-users"
echo "  aws iam list-roles"
echo "  aws iam list-policies --scope Local"
echo "  aws iam get-user --user-name NAME"
echo "  aws iam create-role --role-name R --assume-role-policy-document file://trust.json"
echo "  aws iam attach-role-policy --role-name R --policy-arn ARN"
echo "  aws iam simulate-principal-policy  (test permissions!)"
echo "  aws iam generate-credential-report"
echo "  aws sts get-caller-identity"
echo "  aws sts assume-role --role-arn ARN --role-session-name S"

echo ""
echo "============================================"
echo "   IAM REFERENCE COMPLETE"
echo "============================================"
