#!/bin/bash
# ================================================
# test-automation-reference.sh
# Build and Test Automation Reference
# Author: Asim Raza - Day 43
# ================================================

echo "============================================"
echo "   BUILD AND TEST AUTOMATION REFERENCE"
echo "   Author: Asim Raza - Day 43"
echo "============================================"

echo ""
echo "[ TEST PYRAMID ]"
echo "  Unit Tests (70%):  fast, isolated, many"
echo "  Integration (20%): medium, multiple components"
echo "  E2E Tests (10%):   slow, full system, few"
echo ""
echo "  CI trigger:"
echo "  Every push     → unit tests (fast gate)"
echo "  PR to main     → unit + integration"
echo "  Merge to main  → all including E2E"

echo ""
echo "[ PYTEST COMMANDS ]"
echo "  pytest tests/                          basic"
echo "  pytest tests/ -v                       verbose"
echo "  pytest tests/ -n auto                  parallel"
echo "  pytest tests/ --cov=src                coverage"
echo "  pytest tests/ --cov-fail-under=80      coverage gate"
echo "  pytest tests/ --junit-xml=results.xml  CI reports"
echo "  pytest tests/ --html=report.html       HTML report"
echo "  pytest tests/ -k 'test_add'            filter tests"
echo "  pytest tests/ -m unit                  by marker"
echo "  pytest tests/ --tb=short               short tracebacks"

echo ""
echo "[ COVERAGE REPORTS ]"
echo "  --cov=src                 measure src/ directory"
echo "  --cov-report=term-missing show uncovered lines"
echo "  --cov-report=xml          for SonarQube/Codecov"
echo "  --cov-report=html         human-readable"
echo "  --cov-fail-under=80       fail if below 80%"

echo ""
echo "[ QUALITY GATES ]"
echo "  Coverage minimum: 80% (adjust per team)"
echo "  Lint errors: 0 (strict)"
echo "  Test count: depends on project size"
echo "  Complexity: radon cc -n C"
echo ""
echo "  All gates must pass before:"
echo "  - Merging to main branch"
echo "  - Building Docker image"
echo "  - Deploying to staging"

echo ""
echo "[ CACHING STRATEGY ]"
echo "  Python (recommended):"
echo "  - uses: actions/setup-python@v4"
echo "    with:"
echo "      cache: pip"
echo ""
echo "  Manual cache:"
echo "  key: pip-\${{ hashFiles('requirements.txt') }}"
echo "  restore-keys: pip-"
echo ""
echo "  Docker layers:"
echo "  cache-from: type=gha"
echo "  cache-to: type=gha,mode=max"

echo ""
echo "[ PARALLEL TESTING ]"
echo "  Same job (xdist):"
echo "  pytest -n auto    # use all CPUs"
echo "  pytest -n 4       # use 4 workers"
echo ""
echo "  Different jobs (matrix):"
echo "  strategy:"
echo "    matrix:"
echo "      test-group: [unit, integration, e2e]"
echo ""
echo "  Collect results:"
echo "  needs: [unit, integration, e2e]"
echo "  if: always()"

echo ""
echo "[ ARTIFACTS ]"
echo "  Upload:"
echo "  - uses: actions/upload-artifact@v3"
echo "    with:"
echo "      name: test-results"
echo "      path: results.xml"
echo "      retention-days: 7"
echo ""
echo "  Download:"
echo "  - uses: actions/download-artifact@v3"
echo "    with:"
echo "      name: test-results"

echo ""
echo "============================================"
echo "   REFERENCE COMPLETE"
echo "============================================"
