#!/bin/bash
# ================================================
# cicd-vocabulary.sh
# CI/CD Terms and Concepts Reference
# Author: Asim Raza - Day 39
# ================================================

echo "============================================"
echo "   CI/CD VOCABULARY REFERENCE"
echo "   Author: Asim Raza - Day 39"
echo "============================================"

echo ""
echo "[ CORE TERMS ]"
echo ""
echo "  Pipeline"
echo "    Series of automated stages that code goes through"
echo "    from commit to production"
echo ""
echo "  Stage / Job"
echo "    One logical step in the pipeline"
echo "    e.g., Test, Build, Deploy"
echo ""
echo "  Runner / Agent"
echo "    The server/VM that EXECUTES pipeline steps"
echo "    GitHub: GitHub-hosted runners (free)"
echo "    Jenkins: agents on your own servers"
echo ""
echo "  Artifact"
echo "    Output of a build stage"
echo "    e.g., .jar file, Docker image, .zip file"
echo "    Passed between pipeline stages"
echo ""
echo "  Trigger"
echo "    Event that starts a pipeline"
echo "    push, pull_request, schedule, manual"
echo ""
echo "  Build"
echo "    Compiling/packaging your application"
echo ""
echo "  Deployment"
echo "    Putting the built artifact into an environment"
echo ""
echo "  Environment"
echo "    Where the app runs: dev, staging, production"

echo ""
echo "[ TESTING TERMS ]"
echo ""
echo "  Unit Tests"
echo "    Test individual functions/classes in isolation"
echo "    Fast, many of them, developer writes them"
echo ""
echo "  Integration Tests"
echo "    Test multiple components working together"
echo "    e.g., API + Database interaction"
echo ""
echo "  E2E Tests (End-to-End)"
echo "    Test the whole system like a real user"
echo "    Selenium, Cypress, Playwright"
echo "    Slow, fewer of them"
echo ""
echo "  Smoke Tests"
echo "    Quick basic tests after deployment"
echo "    'Is the app running at all?'"
echo ""
echo "  Regression Tests"
echo "    Ensure old features still work"
echo "    Run after every change"

echo ""
echo "[ DEPLOYMENT TERMS ]"
echo ""
echo "  Rolling Deployment"
echo "    Update instances one batch at a time"
echo "    Zero downtime"
echo ""
echo "  Blue-Green Deployment"
echo "    Two identical environments (blue=old, green=new)"
echo "    Switch traffic from blue to green instantly"
echo "    Instant rollback: switch back to blue"
echo ""
echo "  Canary Deployment"
echo "    Send 5% of traffic to new version first"
echo "    Monitor for problems"
echo "    Gradually increase to 100%"
echo "    Rollback affects only 5% if caught early"
echo ""
echo "  Feature Flags"
echo "    Deploy code but keep feature OFF"
echo "    Enable for specific users/percentage"
echo "    Decouple deployment from release"

echo ""
echo "[ QUALITY TERMS ]"
echo ""
echo "  SAST (Static Application Security Testing)"
echo "    Scan SOURCE CODE for vulnerabilities"
echo "    Before running the app"
echo "    Tool: bandit, SonarQube, Semgrep"
echo ""
echo "  DAST (Dynamic Application Security Testing)"
echo "    Scan RUNNING APP for vulnerabilities"
echo "    Tool: OWASP ZAP, Burp Suite"
echo ""
echo "  SCA (Software Composition Analysis)"
echo "    Check DEPENDENCIES for known CVEs"
echo "    Tool: Snyk, OWASP Dependency-Check"
echo ""
echo "  Code Coverage"
echo "    Percentage of code executed by tests"
echo "    Threshold: typically 80% minimum"

echo ""
echo "[ DORA METRICS ]"
echo "  Deployment Frequency = how often you deploy"
echo "  Lead Time = commit → production time"
echo "  Change Failure Rate = % of deployments failing"
echo "  Recovery Time = how long to fix failure"
echo ""
echo "  Elite: deploy daily, lead time < 1 hour"
echo "  Low:   monthly, lead time months"

echo ""
echo "============================================"
echo "   VOCABULARY COMPLETE"
echo "============================================"
