#!/bin/bash
# ================================================
# devops-culture.sh
# How CI/CD Changes Team Culture
# Author: Asim Raza - Day 39
# ================================================

echo "============================================"
echo "   CI/CD AND DEVOPS CULTURE"
echo "   Author: Asim Raza - Day 39"
echo "============================================"

echo ""
echo "[ HOW CI/CD CHANGES EVERYTHING ]"
echo ""
echo "  BEFORE CI/CD (Waterfall/Manual):"
echo "  ─────────────────────────────────"
echo "  Developers write code for weeks"
echo "  QA tests for weeks"
echo "  Ops deploys once a month"
echo "  Everyone blames everyone else"
echo "  'It works on my machine!'"
echo "  Fear: every deployment is terrifying"
echo "  Rollback: hours or impossible"
echo ""
echo "  AFTER CI/CD (DevOps culture):"
echo "  ─────────────────────────────────"
echo "  Developers push small changes daily"
echo "  Tests run automatically (< 10 min)"
echo "  Deployment is boring and routine"
echo "  Team shares responsibility"
echo "  'Works everywhere because tests say so'"
echo "  Confidence: deploy anytime"
echo "  Rollback: one command, 30 seconds"

echo ""
echo "[ THE SHIFT: DEV + OPS = DEVOPS ]"
echo ""
echo "  Old world:"
echo "  Developer: 'Here's the code, good luck'"
echo "  Operations: 'We can't deploy this, it's broken'"
echo "  → Blame, conflict, slow delivery"
echo ""
echo "  DevOps world:"
echo "  Developer writes code AND tests"
echo "  CI/CD runs the tests automatically"
echo "  Operations provides the pipeline"
echo "  Everyone owns the deployment"
echo "  → Shared ownership, fast delivery"

echo ""
echo "[ THE THREE WAYS OF DEVOPS ]"
echo ""
echo "  First Way: Flow (left to right)"
echo "    Code → Test → Build → Deploy"
echo "    Fast, automated, no handoffs"
echo "    CI/CD enables this"
echo ""
echo "  Second Way: Feedback"
echo "    Monitoring tells you when things break"
echo "    Tests tell you BEFORE deployment"
echo "    Fast feedback loops"
echo ""
echo "  Third Way: Continuous Learning"
echo "    Every failure = learning opportunity"
echo "    Post-mortems without blame"
echo "    Automation prevents repeated mistakes"

echo ""
echo "[ CI/CD PREREQUISITES ]"
echo ""
echo "  Technical:"
echo "  ✅ Version control (Git) - Day 19-25"
echo "  ✅ Automated tests - MUST write tests"
echo "  ✅ Containerization - Day 26-38"
echo "  ✅ Infrastructure as Code - Day 71-80"
echo ""
echo "  Cultural:"
echo "  ✅ Small, frequent commits"
echo "  ✅ Feature branches + pull requests"
echo "  ✅ Everyone writes tests"
echo "  ✅ Deployment is routine, not scary"
echo "  ✅ Monitoring and alerting in place"

echo ""
echo "[ WHY DEVOPS ENGINEERS OWN CI/CD ]"
echo ""
echo "  DevOps engineers BUILD the pipeline"
echo "  (The factory floor, not the products)"
echo ""
echo "  Responsibilities:"
echo "  → Design pipeline stages"
echo "  → Choose and configure tools"
echo "  → Write pipeline config (YAML)"
echo "  → Maintain runner infrastructure"
echo "  → Optimize build speed"
echo "  → Debug pipeline failures"
echo "  → Ensure pipeline security"
echo "  → Onboard new teams to the pipeline"

echo ""
echo "============================================"
echo "   CULTURE SECTION COMPLETE"
echo "============================================"
