#!/bin/bash
# ================================================
# strategy-decision.sh
# Which Deployment Strategy to Use?
# Author: Asim Raza - Day 50
# ================================================

echo "============================================"
echo "   DEPLOYMENT STRATEGY DECISION GUIDE"
echo "   Author: Asim Raza - Day 50"
echo "============================================"

echo ""
echo "[ STRATEGY COMPARISON TABLE ]"
printf "%-20s %-12s %-12s %-12s %-20s\n" \
    "Strategy" "Downtime" "Rollback" "Cost" "Best For"
printf "%-20s %-12s %-12s %-12s %-20s\n" \
    "--------" "--------" "--------" "----" "--------"
printf "%-20s %-12s %-12s %-12s %-20s\n" \
    "Recreate" "YES" "Minutes" "1x" "Dev/DB migrations"
printf "%-20s %-12s %-12s %-12s %-20s\n" \
    "Rolling Update" "NONE" "Seconds" "1.3x" "Most services"
printf "%-20s %-12s %-12s %-12s %-20s\n" \
    "Blue-Green" "NONE" "Instant" "2x" "High-risk/payment"
printf "%-20s %-12s %-12s %-12s %-20s\n" \
    "Canary" "NONE" "Instant" "1.1x" "Algorithm changes"
printf "%-20s %-12s %-12s %-12s %-20s\n" \
    "Feature Flags" "NONE" "Instant" "1x" "Product features"

echo ""
echo "[ DECISION FLOWCHART ]"
echo ""
echo "  Q1: Can you afford any downtime?"
echo "  → NO: Skip Recreate strategy"
echo "  → YES: Recreate is an option (dev/test only)"
echo ""
echo "  Q2: Can v1 and v2 run simultaneously?"
echo "  → NO (DB schema change): Use Recreate with maintenance window"
echo "  → YES: Continue to Q3"
echo ""
echo "  Q3: Need instant rollback capability?"
echo "  → YES (payments, auth): Blue-Green"
echo "  → NO: Continue to Q4"
echo ""
echo "  Q4: Is this a high-risk code change?"
echo "  → YES (algorithm, ML model): Canary"
echo "  → NO: Continue to Q5"
echo ""
echo "  Q5: Is this a product feature?"
echo "  → YES: Feature Flags (decouple deploy/release)"
echo "  → NO: Rolling Update"
echo ""
echo "  DEFAULT: Rolling Update is the right choice"
echo "  for most stateless web services"

echo ""
echo "[ REAL INDUSTRY EXAMPLES ]"
echo ""
echo "  Amazon:"
echo "  Strategy: Canary + Feature Flags"
echo "  Deploy new checkout algorithm to 0.01%"
echo "  Monitor: conversion rate, latency, errors"
echo "  If better: gradually increase to 100%"
echo "  Deploy frequency: 11.7 seconds"
echo ""
echo "  Netflix:"
echo "  Strategy: Canary + Regional rollout"
echo "  Deploy to one AWS region first"
echo "  Monitor: stream quality, error rates"
echo "  If healthy: roll out to all regions"
echo ""
echo "  Stripe (payment processing):"
echo "  Strategy: Blue-Green + Feature Flags"
echo "  Zero downtime absolutely required"
echo "  Instant rollback for financial systems"
echo ""
echo "  Facebook:"
echo "  Strategy: Feature Flags (FBLearner)"
echo "  Code deployed, features off"
echo "  Enable for internal → 1% → 100%"
echo "  Runs thousands of A/B tests simultaneously"

echo ""
echo "[ COMBINING STRATEGIES ]"
echo ""
echo "  Real production uses COMBINATIONS:"
echo ""
echo "  Deployment: Rolling Update (zero downtime)"
echo "  +   Feature: Feature Flag (gradual exposure)"
echo "  +   Monitoring: Canary metrics monitoring"
echo ""
echo "  Flow:"
echo "  1. Rolling update deploys new code (flag OFF)"
echo "  2. Enable flag for 1% of users (canary users)"
echo "  3. Monitor metrics (error rate, latency)"
echo "  4. Increase to 10% → 50% → 100%"
echo "  5. Rollback: disable flag instantly (no redeploy)"

echo ""
echo "[ KUBERNETES ROLLOUT COMMANDS CHEAT SHEET ]"
echo ""
echo "  # Rolling update:"
echo "  kubectl set image deploy/app app=myapp:v2"
echo "  kubectl rollout status deploy/app"
echo "  kubectl rollout undo deploy/app"
echo ""
echo "  # Blue-green switch:"
echo "  kubectl patch svc app-svc \\"
echo "    -p '{\"spec\":{\"selector\":{\"color\":\"green\"}}}'"
echo ""
echo "  # Canary scale:"
echo "  kubectl scale deploy/app-canary --replicas=5"
echo "  kubectl scale deploy/app-stable --replicas=15"
echo ""
echo "  # Check rollout history:"
echo "  kubectl rollout history deploy/app"
echo "  kubectl rollout undo deploy/app --to-revision=3"

echo ""
echo "============================================"
echo "   DECISION GUIDE COMPLETE"
echo "============================================"
