#!/bin/bash
# ================================================
# jenkins-ui-guide.sh
# Jenkins UI Navigation Guide
# Author: Asim Raza - Day 46
# ================================================

echo "============================================"
echo "   JENKINS UI NAVIGATION GUIDE"
echo "   URL: http://localhost:8090"
echo "============================================"

echo ""
echo "[ MAIN DASHBOARD ]"
echo "  URL: http://localhost:8090"
echo "  Shows: All jobs, build status"
echo "  Left panel:"
echo "    - New Item (create job)"
echo "    - People (users)"
echo "    - Build History"
echo "    - Manage Jenkins"

echo ""
echo "[ CREATING A PIPELINE JOB ]"
echo ""
echo "  Step 1: Dashboard → New Item"
echo "  Step 2: Enter name: 'devops-pipeline'"
echo "  Step 3: Select: 'Pipeline'"
echo "  Step 4: Click OK"
echo ""
echo "  In Job Config:"
echo "  ┌─────────────────────────────────┐"
echo "  │ General:                         │"
echo "  │   ☑ Discard old builds          │"
echo "  │   Days: 30, Max: 20             │"
echo "  │                                  │"
echo "  │ Build Triggers:                  │"
echo "  │   ☑ GitHub hook trigger         │"
echo "  │   OR                            │"
echo "  │   ☑ Poll SCM: H/5 * * * *       │"
echo "  │                                  │"
echo "  │ Pipeline:                        │"
echo "  │   Definition: Pipeline script    │"
echo "  │   from SCM                       │"
echo "  │   SCM: Git                       │"
echo "  │   Repository URL: [your repo]   │"
echo "  │   Credentials: github-creds     │"
echo "  │   Branch: */main                │"
echo "  │   Script Path: Jenkinsfile      │"
echo "  └─────────────────────────────────┘"
echo "  Click: Save"

echo ""
echo "[ MANAGE JENKINS ]"
echo "  URL: http://localhost:8090/manage"
echo ""
echo "  System:          Global system config"
echo "  Plugins:         Install/update plugins"
echo "  Nodes:           Agent management"
echo "  Credentials:     Secret management"
echo "  Users:           User management"
echo "  Security:        Auth & authorization"
echo "  Tools:           JDK, Git, Maven config"
echo "  System Log:      Jenkins logs"
echo "  Script Console:  Groovy console"

echo ""
echo "[ CREDENTIALS ]"
echo "  URL: http://localhost:8090/credentials"
echo ""
echo "  Manage Jenkins → Credentials → System"
echo "  → Global credentials → Add credentials"
echo ""
echo "  Credential types:"
echo "  Username with password:"
echo "    GitHub, Docker Hub, database logins"
echo ""
echo "  Secret text:"
echo "    API keys, tokens, webhook URLs"
echo ""
echo "  SSH Username with private key:"
echo "    Server deployment keys"
echo ""
echo "  Certificate:"
echo "    TLS certificates"
echo ""
echo "  Kubernetes cluster:"
echo "    K8s kubeconfig (needs plugin)"

echo ""
echo "[ ADDING GITHUB CREDENTIALS ]"
echo ""
echo "  1. Manage Jenkins → Credentials"
echo "  2. System → Global credentials"
echo "  3. Add Credentials"
echo "  4. Kind: Username with password"
echo "  5. Scope: Global"
echo "  6. Username: Muhammad-Asim-raza"
echo "  7. Password: [GitHub Personal Access Token]"
echo "     (Settings → Developer settings → PAT → Classic)"
echo "  8. ID: github-credentials"
echo "  9. Description: GitHub PAT - Asim Raza"
echo "  10. OK"

echo ""
echo "[ GLOBAL TOOLS CONFIGURATION ]"
echo "  URL: http://localhost:8090/manage/configureTools/"
echo ""
echo "  Manage Jenkins → Tools"
echo ""
echo "  JDK installations:"
echo "  Name: JDK-17"
echo "  JAVA_HOME: /opt/java/openjdk"
echo "  (auto-detected in Docker image)"
echo ""
echo "  Git installations:"
echo "  Name: Default"
echo "  Path to Git executable: git"
echo ""
echo "  Docker installations:"
echo "  Name: Docker"
echo "  Installation root: (auto-detect)"
echo "  OR"
echo "  Add installer → Download from docker.com"

echo ""
echo "[ SYSTEM CONFIGURATION ]"
echo "  URL: http://localhost:8090/manage/configure"
echo ""
echo "  Important settings:"
echo "  Jenkins URL: http://localhost:8090/"
echo "  (Needed for webhooks and links to work)"
echo ""
echo "  System message: (optional)"
echo "  e.g., 'DevOps Learning - Day 46'"
echo ""
echo "  Usage of Nodes:"
echo "  Use only if tied projects: jobs on controller"
echo "  (in production: use dedicated agents)"

echo ""
echo "[ PIPELINE VISUALIZATION ]"
echo "  After running a job:"
echo ""
echo "  Classic view: /job/NAME/NUMBER/"
echo "  Shows: Stage View (colored boxes)"
echo ""
echo "  Blue Ocean: /blue/pipelines/"
echo "  Shows: Modern graph, better logs"
echo "  Access: Open Blue Ocean (left menu)"

echo ""
echo "[ USEFUL JENKINS URLS ]"
echo "  Dashboard:     http://localhost:8090/"
echo "  Manage:        http://localhost:8090/manage"
echo "  Plugins:       http://localhost:8090/pluginManager"
echo "  Credentials:   http://localhost:8090/credentials"
echo "  Nodes:         http://localhost:8090/computer"
echo "  Script console: http://localhost:8090/script"
echo "  API:           http://localhost:8090/api/json"
echo "  Blue Ocean:    http://localhost:8090/blue"

echo ""
echo "============================================"
echo "   UI GUIDE COMPLETE"
echo "============================================"
