#!/bin/bash
# ================================================
# 02-create-vpc.sh
# PRINTABLE AWS VPC LEARNING SCRIPT — NOT RUNNABLE
# ================================================

REGION="${AWS_REGION:-us-east-1}"
VPC_CIDR="10.0.0.0/16"
APP_NAME="devops-journey"

echo "============================================"
echo "       PRODUCTION VPC — LEARNING GUIDE"
echo "       Region: $REGION"
echo "       CIDR: $VPC_CIDR"
echo "       App: $APP_NAME"
echo "============================================"

echo ""
echo "[ STEP 1: CREATE VPC ]"
echo "aws ec2 create-vpc \\"
echo "  --cidr-block $VPC_CIDR \\"
echo "  --tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=${APP_NAME}-vpc},{Key=Environment,Value=production}]' \\"
echo "  --query 'Vpc.VpcId' --output text --region $REGION"
echo ""
echo "Purpose: Creates the VPC and its private IP address range."
echo ""

echo "[ STEP 1B: ENABLE DNS HOSTNAMES ]"
echo "aws ec2 modify-vpc-attribute \\"
echo "  --vpc-id VPC_ID \\"
echo "  --enable-dns-hostnames"
echo ""
echo "Purpose: Allows DNS hostnames for resources that support them."
echo ""

echo "[ STEP 2: CREATE SIX SUBNETS ]"
echo ""
echo "PUBLIC SUBNET A:"
echo "aws ec2 create-subnet --vpc-id VPC_ID --cidr-block 10.0.1.0/24 --availability-zone ${REGION}a"
echo ""
echo "PUBLIC SUBNET B:"
echo "aws ec2 create-subnet --vpc-id VPC_ID --cidr-block 10.0.2.0/24 --availability-zone ${REGION}b"
echo ""
echo "PRIVATE APP SUBNET A:"
echo "aws ec2 create-subnet --vpc-id VPC_ID --cidr-block 10.0.10.0/24 --availability-zone ${REGION}a"
echo ""
echo "PRIVATE APP SUBNET B:"
echo "aws ec2 create-subnet --vpc-id VPC_ID --cidr-block 10.0.11.0/24 --availability-zone ${REGION}b"
echo ""
echo "DATABASE SUBNET A:"
echo "aws ec2 create-subnet --vpc-id VPC_ID --cidr-block 10.0.20.0/24 --availability-zone ${REGION}a"
echo ""
echo "DATABASE SUBNET B:"
echo "aws ec2 create-subnet --vpc-id VPC_ID --cidr-block 10.0.21.0/24 --availability-zone ${REGION}b"
echo ""
echo "Purpose: Separates public, application, and database resources."
echo "Note: Replace VPC_ID with the real VPC ID."
echo ""

echo "[ STEP 2B: AUTO-ASSIGN PUBLIC IPs ]"
echo "aws ec2 modify-subnet-attribute --subnet-id PUBLIC_SUBNET_ID --map-public-ip-on-launch"
echo ""
echo "Purpose: Automatically assigns public IPv4 addresses to instances launched in that subnet."
echo ""

echo "[ STEP 3: CREATE INTERNET GATEWAY ]"
echo "aws ec2 create-internet-gateway"
echo ""
echo "[ STEP 3B: ATTACH INTERNET GATEWAY TO VPC ]"
echo "aws ec2 attach-internet-gateway --internet-gateway-id IGW_ID --vpc-id VPC_ID"
echo ""
echo "Purpose: Connects the VPC to the internet when routes and other requirements are configured."
echo ""

echo "[ STEP 4: CREATE PUBLIC ROUTE TABLE ]"
echo "aws ec2 create-route-table --vpc-id VPC_ID"
echo ""
echo "[ STEP 4B: ADD PUBLIC INTERNET ROUTE ]"
echo "aws ec2 create-route \\"
echo "  --route-table-id PUBLIC_RT_ID \\"
echo "  --destination-cidr-block 0.0.0.0/0 \\"
echo "  --gateway-id IGW_ID"
echo ""
echo "Purpose: Sends internet-bound traffic through the Internet Gateway."
echo "Routes:"
echo "  10.0.0.0/16 -> local"
echo "  0.0.0.0/0   -> Internet Gateway"
echo ""

echo "[ STEP 4C: CREATE PRIVATE ROUTE TABLE ]"
echo "aws ec2 create-route-table --vpc-id VPC_ID"
echo ""
echo "Purpose: Starts with the automatic local VPC route."
echo "No internet route is added in this learning example."
echo ""

echo "[ STEP 4D: ASSOCIATE SUBNETS WITH ROUTE TABLES ]"
echo "aws ec2 associate-route-table --route-table-id PUBLIC_RT_ID --subnet-id PUBLIC_SUBNET_ID"
echo "aws ec2 associate-route-table --route-table-id PRIVATE_RT_ID --subnet-id PRIVATE_SUBNET_ID"
echo "aws ec2 associate-route-table --route-table-id PRIVATE_RT_ID --subnet-id DATABASE_SUBNET_ID"
echo ""
echo "Purpose: Connects each subnet to its intended routing rules."
echo "Note: A separate database route table is optional."
echo ""

echo "[ STEP 5: NAT GATEWAY — EXAMPLE COMMANDS ONLY ]"
echo "WARNING: A NAT Gateway incurs charges. These commands are NOT executed."
echo ""
echo "5A. Allocate an Elastic IP:"
echo "aws ec2 allocate-address --domain vpc"
echo ""
echo "5B. Create NAT Gateway in a PUBLIC subnet:"
echo "aws ec2 create-nat-gateway --subnet-id PUBLIC_SUBNET_ID --allocation-id EIP_ALLOCATION_ID"
echo ""
echo "5C. Wait for the NAT Gateway:"
echo "aws ec2 wait nat-gateway-available --nat-gateway-ids NAT_GW_ID"
echo ""
echo "5D. Add outbound internet routing to the PRIVATE route table:"
echo "aws ec2 create-route \\"
echo "  --route-table-id PRIVATE_RT_ID \\"
echo "  --destination-cidr-block 0.0.0.0/0 \\"
echo "  --nat-gateway-id NAT_GW_ID"
echo ""
echo "Purpose: Allows private instances to initiate outbound internet connections."
echo "Database subnets normally do not need this route."
echo ""

echo "[ VERIFICATION COMMANDS — EXAMPLES ONLY ]"
echo "aws ec2 describe-vpcs --region $REGION"
echo "aws ec2 describe-subnets --region $REGION"
echo "aws ec2 describe-route-tables --region $REGION"
echo "aws ec2 describe-internet-gateways --region $REGION"
echo ""

echo "[ CLEANUP COMMANDS — EXAMPLES ONLY ]"
echo "Delete resources in the correct dependency order."
echo "aws ec2 delete-nat-gateway --nat-gateway-id NAT_GW_ID"
echo "aws ec2 release-address --allocation-id EIP_ALLOCATION_ID"
echo "aws ec2 detach-internet-gateway --internet-gateway-id IGW_ID --vpc-id VPC_ID"
echo "aws ec2 delete-internet-gateway --internet-gateway-id IGW_ID"
echo "aws ec2 delete-subnet --subnet-id SUBNET_ID"
echo "aws ec2 delete-route-table --route-table-id ROUTE_TABLE_ID"
echo "aws ec2 delete-vpc --vpc-id VPC_ID"
echo "Note: Remove custom routes and associations, and delete dependent resources first."
echo ""

echo "============================================"
echo " PRINTABLE GUIDE FINISHED"
echo " NO AWS RESOURCES WERE CREATED"
echo "============================================"
