#!/bin/bash
# ================================================
# 03-vpc-advanced.sh
# VPC Endpoints, Peering, and Flow Logs
# Author: Asim Raza - Day 55
# ================================================

echo "============================================"
echo "   ADVANCED VPC FEATURES"
echo "============================================"

echo ""
echo "[ VPC ENDPOINTS ]"
echo ""
echo "  Problem without endpoints:"
echo "  EC2 in private subnet needs S3"
echo "  Route: EC2 → NAT GW → Internet → S3"
echo "  Cost: NAT GW data transfer fees"
echo "  Security: traffic goes over internet"
echo ""
echo "  VPC Endpoint solution:"
echo "  EC2 → VPC Endpoint → S3 (private AWS network)"
echo "  Cost: no NAT GW fees for S3 traffic"
echo "  Security: traffic NEVER leaves AWS network"
echo ""
echo "  TWO TYPES:"
echo ""
echo "  Gateway Endpoint (free):"
echo "  Services: S3 and DynamoDB ONLY"
echo "  Added to route table as target"
echo "  aws ec2 create-vpc-endpoint \\"
echo "    --vpc-id vpc-xxx \\"
echo "    --service-name com.amazonaws.us-east-1.s3 \\"
echo "    --vpc-endpoint-type Gateway \\"
echo "    --route-table-ids rtb-PRIVATE"
echo ""
echo "  Interface Endpoint (costs ~\$7/month):"
echo "  Services: most other AWS services"
echo "  Creates an ENI (Elastic Network Interface)"
echo "  Uses PrivateLink technology"
echo "  Services: EC2 API, SSM, Secrets Manager, ECR..."
echo "  aws ec2 create-vpc-endpoint \\"
echo "    --vpc-id vpc-xxx \\"
echo "    --service-name com.amazonaws.us-east-1.ecr.api \\"
echo "    --vpc-endpoint-type Interface \\"
echo "    --subnet-ids subnet-PRIVATE \\"
echo "    --security-group-ids sg-xxx"

echo ""
echo "[ VPC PEERING ]"
echo ""
echo "  Connect TWO VPCs so they can communicate"
echo "  Traffic stays on AWS private network"
echo "  Works across: regions and accounts"
echo ""
echo "  Use cases:"
echo "  Shared services VPC → spoke VPCs"
echo "  Development VPC → Production VPC (read-only)"
echo "  Company A VPC → Company B VPC (partner)"
echo ""
echo "  LIMITATIONS:"
echo "  NO transitive routing!"
echo "  VPC-A peered with VPC-B"
echo "  VPC-B peered with VPC-C"
echo "  VPC-A CANNOT reach VPC-C"
echo "  (must peer A-C directly)"
echo ""
echo "  For hub-and-spoke: use Transit Gateway"
echo "  (more expensive but scales better)"
echo ""
echo "  CREATE PEERING:"
echo "  # From requesting VPC:"
echo "  aws ec2 create-vpc-peering-connection \\"
echo "    --vpc-id vpc-REQUESTER \\"
echo "    --peer-vpc-id vpc-ACCEPTER \\"
echo "    --peer-region us-west-2"
echo ""
echo "  # Accept from the other side:"
echo "  aws ec2 accept-vpc-peering-connection \\"
echo "    --vpc-peering-connection-id pcx-xxx"
echo ""
echo "  # Add routes in BOTH VPCs:"
echo "  aws ec2 create-route \\"
echo "    --route-table-id rtb-VPC-A \\"
echo "    --destination-cidr-block 10.1.0.0/16 \\"
echo "    --vpc-peering-connection-id pcx-xxx"

echo ""
echo "[ VPC FLOW LOGS ]"
echo ""
echo "  Captures IP traffic information for:"
echo "  Network interfaces, subnets, or entire VPC"
echo ""
echo "  What flow logs capture:"
echo "  Source IP, Destination IP"
echo "  Source port, Destination port"
echo "  Protocol (TCP=6, UDP=17)"
echo "  Bytes and packets"
echo "  Action: ACCEPT or REJECT"
echo "  Timestamp"
echo ""
echo "  Destination: CloudWatch Logs or S3"
echo ""
echo "  Create VPC Flow Log:"
echo "  aws ec2 create-flow-logs \\"
echo "    --resource-type VPC \\"
echo "    --resource-ids vpc-xxx \\"
echo "    --traffic-type ALL \\"
echo "    --log-destination-type cloud-watch-logs \\"
echo "    --log-group-name /aws/vpc/flowlogs \\"
echo "    --deliver-logs-permission-arn arn:aws:iam::xxx:role/FlowLogsRole"
echo ""
echo "  Use for:"
echo "  Security: who is connecting to what"
echo "  Debugging: why is traffic rejected"
echo "  Compliance: connection audit trail"
echo "  Cost: data transfer analysis"

echo ""
echo "[ DEFAULT VPC ]"
echo ""
echo "  AWS creates a default VPC in every region"
echo "  CIDR: 172.31.0.0/16"
echo "  One default subnet per AZ"
echo "  Has IGW already attached"
echo "  All subnets are PUBLIC"
echo ""
echo "  Use for: quick tests and learning"
echo "  NEVER for: production workloads"
echo ""
echo "  Default VPC characteristics:"
echo "  ✓ Quick to get started"
echo "  ✗ All instances public by default"
echo "  ✗ Cannot customize CIDR easily"
echo "  ✗ Not suitable for production"

echo ""
echo "============================================"
echo "   ADVANCED VPC FEATURES COMPLETE"
echo "============================================"
