#!/bin/bash
# ================================================
# docker-cicd-reference.sh
# Docker in CI/CD Complete Reference
# Author: Asim Raza - Day 44
# ================================================

echo "============================================"
echo "   DOCKER IN GITHUB ACTIONS REFERENCE"
echo "   Author: Asim Raza - Day 44"
echo "============================================"

echo ""
echo "[ KEY ACTIONS ]"
echo "  docker/setup-buildx-action@v3"
echo "    Enables BuildKit, multi-platform"
echo ""
echo "  docker/setup-qemu-action@v3"
echo "    Enables cross-platform builds"
echo "    (arm64 on amd64 runner)"
echo ""
echo "  docker/login-action@v3"
echo "    Login to any registry"
echo "    Docker Hub: username + token"
echo "    GHCR: github.actor + GITHUB_TOKEN"
echo "    ECR: via OIDC (Phase 6)"
echo ""
echo "  docker/metadata-action@v5"
echo "    Generates tags and labels"
echo "    type=sha, type=semver, type=raw"
echo ""
echo "  docker/build-push-action@v5"
echo "    Build + push in one step"
echo "    Supports caching, multi-platform"

echo ""
echo "[ REGISTRY OPTIONS ]"
echo "  Docker Hub:  docker.io/username/image"
echo "  GHCR:        ghcr.io/org/repo"
echo "  AWS ECR:     account.dkr.ecr.region.amazonaws.com/image"
echo "  GCP GCR:     gcr.io/project/image"
echo ""
echo "  GHCR Auth:   GITHUB_TOKEN (automatic!)"
echo "  Docker Hub:  DOCKERHUB_USERNAME + DOCKERHUB_TOKEN"
echo "  ECR:         OIDC role (Phase 6)"

echo ""
echo "[ IMAGE TAGGING STRATEGY ]"
echo "  git SHA (immutable):"
echo "  sha-abc1234 = exact commit"
echo "  Never changes, always traceable"
echo ""
echo "  semantic version (release):"
echo "  v1.2.3 = human-readable release"
echo ""
echo "  latest (convenience):"
echo "  latest = most recent main build"
echo "  NEVER use in production deployments!"
echo ""
echo "  PR builds:"
echo "  pr-42 = PR number"
echo "  Test without polluting production tags"

echo ""
echo "[ BUILD ARGS PATTERN ]"
echo "  In workflow:"
echo "  build-args: |"
echo "    APP_VERSION=\${{ steps.ver.outputs.version }}"
echo "    GIT_COMMIT=\${{ github.sha }}"
echo "    BUILD_TIME=\$(date -u)"
echo "    GIT_BRANCH=\${{ github.ref_name }}"
echo ""
echo "  In Dockerfile:"
echo "  ARG APP_VERSION=dev"
echo "  ENV APP_VERSION=\${APP_VERSION}"

echo ""
echo "[ CACHING LAYERS ]"
echo "  cache-from: type=gha"
echo "  cache-to: type=gha,mode=max"
echo ""
echo "  Without cache: 2-5 minutes per build"
echo "  With cache: 15-30 seconds per build"

echo ""
echo "[ SECURITY SCANNING ]"
echo "  uses: aquasecurity/trivy-action@master"
echo "  with:"
echo "    image-ref: my-image:tag"
echo "    severity: CRITICAL,HIGH"
echo "    exit-code: 1   # fail on CVEs"

echo ""
echo "[ MULTI-PLATFORM ]"
echo "  1. Setup QEMU:    docker/setup-qemu-action"
echo "  2. Setup Buildx:  docker/setup-buildx-action"
echo "  3. Build:         platforms: linux/amd64,linux/arm64"
echo ""
echo "  Result: one tag, two architectures"
echo "  Docker pulls correct one automatically"

echo ""
echo "[ WORKFLOWS CREATED TODAY ]"
for wf in 20 21 22 23; do
    ls ~/DevOps-journey/.github/workflows/${wf}-*.yml \
        2>/dev/null | xargs -I{} basename {}
done

echo ""
echo "============================================"
echo "   REFERENCE COMPLETE"
echo "============================================"
