#!/bin/bash
# ================================================
# vpc-designer.sh
# VPC Architecture Designer and Validator
# Author: Asim Raza
# Day 15 of DevOps Journey
# ================================================

echo "============================================"
echo "   VPC ARCHITECTURE DESIGNER"
echo "   Author: Asim Raza - Day 15"
echo "============================================"

# VPC Configuration
VPC_CIDR="10.0.0.0/16"
REGION="us-east-1"

echo ""
echo "[ VPC CONFIGURATION ]"
echo "VPC CIDR    : $VPC_CIDR"
echo "Region      : $REGION"
echo "Purpose     : Production 3-tier application"

echo ""
echo "[ SUBNET DESIGN ]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Define subnets
declare -A SUBNETS
SUBNETS[public_a]="10.0.1.0/24:PUBLIC:us-east-1a:Load Balancer Web"
SUBNETS[public_b]="10.0.2.0/24:PUBLIC:us-east-1b:Load Balancer Web"
SUBNETS[private_a]="10.0.10.0/24:PRIVATE:us-east-1a:Application Servers"
SUBNETS[private_b]="10.0.11.0/24:PRIVATE:us-east-1b:Application Servers"
SUBNETS[db_a]="10.0.20.0/26:PRIVATE:us-east-1a:Database Primary"
SUBNETS[db_b]="10.0.21.0/26:PRIVATE:us-east-1b:Database Standby"

echo "Name            CIDR            Type     AZ          Purpose"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
for SUBNET_NAME in "${!SUBNETS[@]}"; do
    IFS=':' read -r CIDR TYPE AZ PURPOSE <<< "${SUBNETS[$SUBNET_NAME]}"
    printf "%-16s %-16s %-9s %-12s %s\n" \
        "$SUBNET_NAME" "$CIDR" "$TYPE" "$AZ" "$PURPOSE"
done | sort

echo ""
echo "[ ROUTE TABLES ]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Public Route Table:"
echo "  Destination    Target"
echo "  10.0.0.0/16 → local (VPC internal)"
echo "  0.0.0.0/0   → Internet Gateway"
echo "  → Attached to: public_a, public_b"
echo ""
echo "Private Route Table:"
echo "  Destination    Target"
echo "  10.0.0.0/16 → local (VPC internal)"
echo "  0.0.0.0/0   → NAT Gateway"
echo "  → Attached to: private_a, private_b"
echo ""
echo "Database Route Table:"
echo "  Destination    Target"
echo "  10.0.0.0/16 → local (VPC internal)"
echo "  (no internet route = completely isolated)"
echo "  → Attached to: db_a, db_b"

echo ""
echo "[ SECURITY GROUPS ]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "sg-load-balancer:"
echo "  Inbound:  80/tcp   0.0.0.0/0 (HTTP from anywhere)"
echo "  Inbound:  443/tcp  0.0.0.0/0 (HTTPS from anywhere)"
echo "  Outbound: all      0.0.0.0/0"
echo ""
echo "sg-application:"
echo "  Inbound:  3000/tcp sg-load-balancer (from LB only)"
echo "  Inbound:  22/tcp   10.0.0.0/16 (SSH from VPC)"
echo "  Outbound: all      0.0.0.0/0"
echo ""
echo "sg-database:"
echo "  Inbound:  5432/tcp sg-application (from app only)"
echo "  Outbound: all      10.0.0.0/16 (VPC only)"
echo ""
echo "sg-bastion:"
echo "  Inbound:  22/tcp   YOUR-OFFICE-IP/32 (SSH from office)"
echo "  Outbound: 22/tcp   10.0.0.0/16 (SSH to VPC)"

echo ""
echo "[ TRAFFIC FLOW ANALYSIS ]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "User Request Flow:"
echo "  Internet"
echo "  → Internet Gateway"
echo "  → Load Balancer (public subnet)"
echo "  → Application Server (private subnet)"
echo "  → Database (db subnet)"
echo "  → Response follows same path back"
echo ""
echo "Admin SSH Flow:"
echo "  Admin laptop"
echo "  → Internet Gateway"
echo "  → Bastion Host (public subnet, port 22)"
echo "  → App Server (private subnet, port 22)"
echo "  (database accessible from app server)"
echo ""
echo "Outbound Update Flow:"
echo "  App Server (private subnet)"
echo "  → NAT Gateway (public subnet)"
echo "  → Internet Gateway"
echo "  → Package repositories"
echo "  (internet cannot initiate connection back)"

echo ""
echo "[ SECURITY ASSESSMENT ]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Database not accessible from internet"
echo "✅ App servers not directly exposed"
echo "✅ Load balancer only accepts 80/443"
echo "✅ SSH restricted to bastion host"
echo "✅ NAT allows outbound not inbound"
echo "✅ Multi-AZ for high availability"
echo "✅ Separate security groups per tier"
echo "✅ Database subnet has no internet route"

echo ""
echo "============================================"
echo "   VPC DESIGN COMPLETE"
echo "============================================"
