#!/bin/bash
# ================================================
# dockerfile-reference.sh
# Complete Dockerfile Reference and Best Practices
# Author: Asim Raza
# Day 28 of DevOps Journey
# ================================================

echo "============================================"
echo "   DOCKERFILE COMPLETE REFERENCE"
echo "   Author: Asim Raza - Day 28"
echo "============================================"

echo ""
echo "[ DOCKERFILE INSTRUCTIONS ]"
echo ""
echo "  FROM image:tag              = base image (REQUIRED, first)"
echo "  FROM image AS name          = named stage (multi-stage)"
echo ""
echo "  RUN command                 = execute during BUILD"
echo "  RUN cmd1 && cmd2            = combine (fewer layers)"
echo ""
echo "  COPY src dest               = copy from host to image"
echo "  COPY --from=stage src dest  = copy from another stage"
echo ""
echo "  ADD src dest                = like COPY + tar extract"
echo ""
echo "  WORKDIR /path               = set working directory"
echo ""
echo "  ENV VAR=value               = runtime environment var"
echo "  ARG VAR=default             = build-time variable only"
echo ""
echo "  EXPOSE port                 = document port (not publish!)"
echo ""
echo "  USER username               = run as this user"
echo ""
echo "  LABEL key=value             = image metadata"
echo ""
echo "  VOLUME /path                = declare mount point"
echo ""
echo "  CMD [\"cmd\", \"arg\"]          = default startup command"
echo "  ENTRYPOINT [\"cmd\"]          = fixed entrypoint"
echo ""
echo "  HEALTHCHECK --interval=30s CMD curl health-url"
echo "                              = container health monitoring"
echo ""
echo "[ KEY BEST PRACTICES ]"
echo ""
echo "  1. Use specific tags (FROM python:3.11-slim NOT :latest)"
echo "  2. Order: packages before code (layer caching)"
echo "  3. Combine RUN commands (fewer layers = smaller image)"
echo "  4. Use .dockerignore (exclude node_modules .env etc)"
echo "  5. Run as non-root user (security)"
echo "  6. Use multi-stage builds (smaller final image)"
echo "  7. Add HEALTHCHECK (Docker monitors your container)"
echo "  8. Set ENV PYTHONUNBUFFERED=1 for Python apps"
echo "  9. Clean apt cache in same RUN: && rm -rf /var/lib/apt/lists/*"
echo " 10. Use --no-cache-dir for pip (smaller image)"

echo ""
echo "[ LAYER CACHING RULES ]"
echo ""
echo "  Put RARELY changing instructions FIRST:"
echo "  FROM → RUN apt install → COPY requirements → RUN pip install"
echo ""
echo "  Put FREQUENTLY changing instructions LAST:"
echo "  COPY app code → CMD"
echo ""
echo "  When a layer changes = ALL layers below it rebuild"
echo "  When a layer is unchanged = CACHE HIT (very fast)"

echo ""
echo "[ CMD vs ENTRYPOINT ]"
echo ""
echo "  CMD [\"python3\", \"app.py\"]"
echo "  = default command, CAN be overridden:"
echo "  docker run myimage bash  ← overrides CMD"
echo ""
echo "  ENTRYPOINT [\"python3\"]"
echo "  CMD [\"app.py\"]"
echo "  = python3 is fixed, app.py is the argument"
echo "  docker run myimage other.py  ← runs python3 other.py"
echo ""
echo "  Use CMD alone for flexibility"
echo "  Use ENTRYPOINT+CMD for wrapper scripts"

echo ""
echo "[ IMAGE SIZE COMPARISON ]"
docker images | grep -E \
    "devops-python|devops-node|multi-stage|devops-production" \
    2>/dev/null | \
    awk '{printf "  %-35s %s\n", $1":"$2, $7}' || \
    echo "  (build images first to see comparison)"

echo ""
echo "[ BUILD COMMANDS ]"
echo "  docker build -t name:tag ."
echo "  docker build --no-cache -t name:tag ."
echo "  docker build --target stage -t name:tag ."
echo "  docker build --build-arg VAR=val -t name:tag ."
echo "  docker build -f OtherDockerfile -t name:tag ."

echo ""
echo "============================================"
echo "   REFERENCE COMPLETE"
echo "============================================"
