#!/bin/bash
# ================================================
# docker-networking.sh
# Docker Networking Complete Reference
# Author: Asim Raza
# Day 30 of DevOps Journey
# ================================================

echo "============================================"
echo "   DOCKER NETWORKING REFERENCE"
echo "   Author: Asim Raza - Day 30"
echo "============================================"

echo ""
echo "[ NETWORK TYPES ]"
echo ""
echo "  bridge (default)"
echo "    --network bridge"
echo "    Virtual network on host"
echo "    Containers get private IPs"
echo "    Isolated from host network"
echo "    Default: no DNS by name"
echo ""
echo "  Custom bridge (recommended)"
echo "    docker network create mynet"
echo "    --network mynet"
echo "    Automatic DNS by container name!"
echo "    Isolated from other networks"
echo "    Best for: application containers"
echo ""
echo "  host"
echo "    --network host"
echo "    Shares host network stack"
echo "    No isolation at all"
echo "    Best for: network tools, monitoring"
echo ""
echo "  none"
echo "    --network none"
echo "    No network access"
echo "    Maximum isolation"
echo "    Best for: security critical workloads"

echo ""
echo "[ NETWORK COMMANDS ]"
echo "  docker network ls                    = list all"
echo "  docker network create name           = create"
echo "  docker network create --subnet x     = with subnet"
echo "  docker network inspect name          = details"
echo "  docker network connect net container = connect"
echo "  docker network disconnect net cont   = disconnect"
echo "  docker network rm name               = delete"
echo "  docker network prune                 = remove unused"

echo ""
echo "[ CONTAINER NETWORKING FLAGS ]"
echo "  --network name       = connect to network"
echo "  --ip 10.0.1.100     = assign specific IP"
echo "  --hostname myhost   = set container hostname"
echo "  --add-host h:ip     = add /etc/hosts entry"
echo "  --dns 8.8.8.8       = custom DNS server"
echo "  --link (deprecated) = old container linking"

echo ""
echo "[ DNS RESOLUTION ]"
echo "  Custom networks: container name → IP (automatic)"
echo "  Default bridge: NO DNS (use IP only)"
echo ""
echo "  Example:"
echo "  docker run --network mynet --name db postgres"
echo "  docker run --network mynet --name app myapp"
echo "  In app: DB_HOST=db (uses container name!)"

echo ""
echo "[ MULTI-TIER NETWORK PATTERN ]"
echo ""
echo "  Internet"
echo "     │"
echo "  ┌──▼──────────────────┐"
echo "  │ frontend-network    │"
echo "  │   [nginx] [backend] │"
echo "  └──────────┬──────────┘"
echo "             │"
echo "  ┌──────────▼──────────┐"
echo "  │ backend-network     │"
echo "  │   [backend] [db]    │"
echo "  │   [backend] [redis] │"
echo "  └─────────────────────┘"
echo ""
echo "  nginx exposed: -p 80:80"
echo "  database: NOT exposed (no -p)"
echo "  backend: bridge between networks"

echo ""
echo "[ CURRENT NETWORKS ]"
docker network ls

echo ""
echo "[ PORT EXPOSURE REMINDER ]"
echo "  Containers on same network: ALL PORTS accessible"
echo "  No -p needed for container-to-container"
echo "  -p only for host → container access"
echo ""
echo "  Container A → Container B on same network:"
echo "  http://container-b:8000  (no port mapping needed)"
echo ""
echo "  External → Container:"
echo "  docker run -p 8080:80 nginx"
echo "  localhost:8080  (port mapping required)"

echo ""
echo "============================================"
echo "   REFERENCE COMPLETE"
echo "============================================"
