#!/bin/bash
# ================================================
# 02-arn-format.sh
# AWS ARN (Amazon Resource Name) Format Guide
# Author: Asim Raza - Day 54
# ================================================

echo "============================================"
echo "   ARN FORMAT EXPLAINED"
echo "   arn:partition:service:region:account:resource"
echo "============================================"
echo ""
echo "  ARN = Amazon Resource Name"
echo "  Unique identifier for EVERY AWS resource"
echo "  Used in: policies, CLI commands, SDK calls"

echo ""
echo "[ ARN FORMAT ]"
echo "  arn:partition:service:region:account-id:resource"
echo ""
echo "  partition: aws (standard), aws-cn (China), aws-us-gov"
echo "  service:   ec2, s3, iam, rds, lambda..."
echo "  region:    us-east-1, eu-west-1, ap-southeast-1..."
echo "             (empty for global services: IAM, S3)"
echo "  account:   12-digit AWS account number"
echo "  resource:  resource type/name/path"

echo ""
echo "[ REAL ARN EXAMPLES ]"
echo ""
echo "  IAM User:"
echo "  arn:aws:iam::123456789012:user/asim-raza"
echo "              ^  ^           ^"
echo "              |  |           resource"
echo "              |  account ID"
echo "              no region (IAM is global)"
echo ""
echo "  IAM Role:"
echo "  arn:aws:iam::123456789012:role/github-actions-role"
echo ""
echo "  EC2 Instance:"
echo "  arn:aws:ec2:us-east-1:123456789012:instance/i-0abc123def456"
echo "                        ^             ^"
echo "                        |             resource"
echo "                        region IS required for EC2"
echo ""
echo "  S3 Bucket:"
echo "  arn:aws:s3:::my-unique-bucket-name"
echo "            ^ ^"
echo "            | no account (S3 names globally unique)"
echo "            no region (S3 is global namespace)"
echo ""
echo "  S3 Object:"
echo "  arn:aws:s3:::my-bucket/folder/file.txt"
echo ""
echo "  Lambda Function:"
echo "  arn:aws:lambda:us-east-1:123456789012:function:my-function"
echo ""
echo "  RDS Database:"
echo "  arn:aws:rds:us-east-1:123456789012:db:my-database"
echo ""
echo "  SNS Topic:"
echo "  arn:aws:sns:us-east-1:123456789012:my-topic"
echo ""
echo "  KMS Key:"
echo "  arn:aws:kms:us-east-1:123456789012:key/mrk-abc123"

echo ""
echo "[ WILDCARDS IN ARNS ]"
echo ""
echo "  * = wildcard (matches anything)"
echo ""
echo "  All S3 objects in bucket:"
echo "  arn:aws:s3:::my-bucket/*"
echo ""
echo "  All EC2 instances:"
echo "  arn:aws:ec2:us-east-1:123456789012:instance/*"
echo ""
echo "  ALL resources (DANGEROUS!):"
echo "  *"
echo "  Use ONLY for emergency break-glass policies"

echo ""
echo "[ GET YOUR ARN ]"
echo "  aws sts get-caller-identity"
echo "  Shows: Account, UserId, Arn"
echo ""
if command -v aws &>/dev/null; then
    aws sts get-caller-identity 2>/dev/null || \
        echo "  (Configure credentials first)"
fi

echo ""
echo "============================================"
echo "   ARN GUIDE COMPLETE"
echo "============================================"
