#!/bin/bash
# ================================================
# 03-policy-types.sh
# IAM Policy Types Reference
# Author: Asim Raza - Day 54
# ================================================

echo "============================================"
echo "   IAM POLICY TYPES"
echo "============================================"

echo ""
echo "[ TYPE 1: AWS MANAGED POLICIES ]"
echo ""
echo "  Pre-built by AWS for common use cases"
echo "  You CANNOT modify them"
echo "  AWS updates them when services change"
echo ""
echo "  Examples:"
echo "  AdministratorAccess    = FULL access to everything"
echo "  PowerUserAccess        = Full access except IAM"
echo "  ReadOnlyAccess         = Read everything, change nothing"
echo "  AmazonS3FullAccess     = Full S3 access"
echo "  AmazonS3ReadOnlyAccess = Read S3 only"
echo "  AmazonEC2FullAccess    = Full EC2 access"
echo "  AWSLambdaBasicExecution= Lambda write logs only"
echo "  AmazonRDSFullAccess    = Full RDS access"
echo ""
echo "  ⚠️  WARNING: AWS managed policies are BROAD"
echo "  AdministratorAccess = dangerous to use broadly"
echo "  AmazonS3FullAccess = access ALL S3 buckets!"
echo "  Use for: quick tests, learning, emergencies only"

echo ""
echo "[ TYPE 2: CUSTOMER MANAGED POLICIES ]"
echo ""
echo "  YOU create and manage them"
echo "  Reusable across multiple users/roles"
echo "  Version controlled (up to 5 versions)"
echo ""
echo "  Best practice for production:"
echo "  Create specific policies per use case"
echo "  Example: 'AppServerS3ReadPolicy'"
echo "  Only access to specific bucket needed"
echo ""
echo "  Creating via CLI:"
echo "  aws iam create-policy \\"
echo "    --policy-name MyAppS3Policy \\"
echo "    --policy-document file://policy.json"

echo ""
echo "[ TYPE 3: INLINE POLICIES ]"
echo ""
echo "  Embedded DIRECTLY in a user/role"
echo "  One-to-one relationship"
echo "  Cannot be reused"
echo "  Deleted when user/role deleted"
echo ""
echo "  ⚠️  AVOID inline policies:"
echo "  Hard to audit (not in policy list)"
echo "  Cannot be reused"
echo "  Hard to maintain at scale"
echo ""
echo "  ONLY use inline when:"
echo "  Policy must not be accidentally attached elsewhere"

echo ""
echo "[ TYPE 4: RESOURCE-BASED POLICIES ]"
echo ""
echo "  Attached TO the resource (not the identity)"
echo "  Specifies WHO can access THIS resource"
echo ""
echo "  Examples:"
echo "  S3 Bucket Policy:"
echo "  {'Principal': {'AWS': 'arn:...user/jenkins'},"
echo "   'Action': ['s3:GetObject'],"
echo "   'Resource': 'arn:aws:s3:::my-bucket/*'}"
echo ""
echo "  Allows: CROSS-ACCOUNT access"
echo "  Account A's S3 → Account B's EC2 can access"
echo ""
echo "  Services with resource policies:"
echo "  S3, SNS, SQS, Lambda, KMS, API Gateway"

echo ""
echo "[ TYPE 5: SERVICE CONTROL POLICIES (SCPs) ]"
echo ""
echo "  Used in AWS Organizations"
echo "  Apply to ENTIRE accounts or OUs"
echo "  MAXIMUM permission boundary"
echo "  Even root user cannot exceed SCP"
echo ""
echo "  Example: Organization SCP:"
echo "  Deny ANY action outside us-east-1 and eu-west-1"
echo "  No matter what IAM policies say"
echo "  Guarantees: no resources created in wrong region"

echo ""
echo "[ POLICY EVALUATION ORDER ]"
echo ""
echo "  1. Check SCPs (Organizations)"
echo "     If SCP Denies → STOP (Deny)"
echo "  2. Check Resource-based policies"
echo "  3. Check Identity-based policies"
echo "  4. Check Permission Boundaries"
echo "  5. Check Session Policies"
echo ""
echo "  DEFAULT: DENY (if no Allow → Deny)"
echo "  Explicit DENY always wins over Allow"
echo "  ALLOW only wins if no Deny exists anywhere"

echo ""
echo "============================================"
echo "   POLICY TYPES COMPLETE"
echo "============================================"
