#!/bin/bash
# ================================================
# production-patterns-reference.sh
# Docker Production Patterns Reference
# Author: Asim Raza
# Day 35 of DevOps Journey
# ================================================

echo "============================================"
echo "   DOCKER PRODUCTION PATTERNS"
echo "   Author: Asim Raza - Day 35"
echo "============================================"

echo ""
echo "[ PRODUCTION READINESS CHECKLIST ]"
echo ""
echo "  IMAGE:"
echo "  ✅ Specific version tag (never :latest)"
echo "  ✅ Multi-stage build (minimal size)"
echo "  ✅ Non-root user (USER appuser)"
echo "  ✅ Health check defined"
echo "  ✅ No secrets in image"
echo "  ✅ Labels with version/date/commit"
echo "  ✅ Vulnerability scanned (trivy)"
echo ""
echo "  CONTAINER:"
echo "  ✅ --read-only filesystem"
echo "  ✅ --cap-drop ALL"
echo "  ✅ --security-opt no-new-privileges"
echo "  ✅ --memory and --cpus limits"
echo "  ✅ --restart unless-stopped"
echo "  ✅ Log rotation configured"
echo "  ✅ --stop-timeout sufficient"
echo ""
echo "  ARCHITECTURE:"
echo "  ✅ Custom networks (not default bridge)"
echo "  ✅ DB on internal network only"
echo "  ✅ Only proxy exposed (-p flag)"
echo "  ✅ Named volumes for data"

echo ""
echo "[ HEALTH CHECK PATTERNS ]"
echo ""
echo "  HTTP (most common):"
echo "  HEALTHCHECK --interval=30s --timeout=5s \\"
echo "    --start-period=20s --retries=3 \\"
echo "    CMD curl -f http://localhost/health"
echo ""
echo "  TCP (databases, non-HTTP):"
echo "  HEALTHCHECK CMD nc -z localhost 5432"
echo ""
echo "  Custom Python:"
echo "  HEALTHCHECK CMD python3 -c \\"
echo "    \"import urllib.request; \\"
echo "     urllib.request.urlopen('http://localhost/health')\""
echo ""
echo "  PostgreSQL:"
echo "  HEALTHCHECK CMD pg_isready -U user -d db"
echo ""
echo "  Redis:"
echo "  HEALTHCHECK CMD redis-cli ping"

echo ""
echo "[ GRACEFUL SHUTDOWN ]"
echo ""
echo "  In Dockerfile:"
echo "  STOPSIGNAL SIGTERM"
echo ""
echo "  In docker run:"
echo "  docker stop --time 30 container"
echo "  (default: 10 seconds - often too short)"
echo ""
echo "  In Compose:"
echo "  stop_grace_period: 35s"
echo ""
echo "  In application:"
echo "  signal.signal(signal.SIGTERM, handle_sigterm)"
echo "  - Stop accepting new requests"
echo "  - Finish in-flight requests"
echo "  - Close DB connections"
echo "  - Exit cleanly"

echo ""
echo "[ LOG CONFIGURATION ]"
echo ""
echo "  Per container:"
echo "  docker run \\"
echo "    --log-driver json-file \\"
echo "    --log-opt max-size=10m \\"
echo "    --log-opt max-file=3 \\"
echo "    myapp:v1.0"
echo ""
echo "  In Compose:"
echo "  logging:"
echo "    driver: json-file"
echo "    options:"
echo "      max-size: \"10m\""
echo "      max-file: \"3\""
echo ""
echo "  Log drivers:"
echo "  json-file = local files (default)"
echo "  awslogs   = AWS CloudWatch"
echo "  fluentd   = Fluentd aggregator"
echo "  syslog    = system syslog"
echo "  none      = discard logs"

echo ""
echo "[ COMPOSE YAML ANCHORS ]"
echo ""
echo "  Define once:"
echo "  x-logging: &logging"
echo "    driver: json-file"
echo "    options:"
echo "      max-size: 10m"
echo ""
echo "  Use anywhere:"
echo "  services:"
echo "    web:"
echo "      logging: *logging  ← uses anchor"
echo "    api:"
echo "      logging: *logging  ← uses same anchor"

echo ""
echo "[ NETWORK SECURITY PATTERN ]"
echo ""
echo "  networks:"
echo "    frontend:"
echo "      driver: bridge"
echo "    backend:"
echo "      driver: bridge"
echo "      internal: true  ← no internet access!"
echo ""
echo "  nginx: [frontend]           (internet-facing)"
echo "  app:   [frontend, backend]  (bridge)"
echo "  db:    [backend]            (isolated)"
echo ""
echo "  Result: DB cannot be reached from internet"
echo "          DB cannot make outbound requests"

echo ""
echo "[ REQUIRED VARIABLES ]"
echo ""
echo "  # Fail if not set:"
echo "  DB_PASSWORD: \${DB_PASSWORD:?DB_PASSWORD required}"
echo ""
echo "  # Use default if not set:"
echo "  LOG_LEVEL: \${LOG_LEVEL:-INFO}"
echo ""
echo "  # Use default, but warn in docs:"
echo "  APP_VERSION: \${APP_VERSION:-1.0.0}"

echo ""
echo "============================================"
echo "   REFERENCE COMPLETE"
echo "============================================"
