#!/bin/bash
# ================================================
# 01-aws-account-setup.sh
# AWS Account Setup Guide
# Author: Asim Raza - Day 53
# ================================================

echo "============================================"
echo "   AWS ACCOUNT SETUP GUIDE"
echo "   Day 53 - AWS Fundamentals"
echo "============================================"

echo ""
echo "[ STEP 1: Create AWS Free Tier Account ]"
echo ""
echo "  URL: https://aws.amazon.com/free"
echo "  Click: 'Create an AWS Account'"
echo ""
echo "  Required:"
echo "  - Email address (use dedicated DevOps email)"
echo "  - Credit/debit card (NOT charged for free tier)"
echo "  - Phone number (verification)"
echo ""
echo "  Account types:"
echo "  ROOT ACCOUNT: your first login email"
echo "    → Use ONLY for billing and initial setup"
echo "    → Never use for daily work"
echo "    → Enable MFA immediately"
echo ""
echo "  IAM USER: what you create for daily work"
echo "    → Create after root setup"
echo "    → Limited permissions"
echo "    → We cover IAM in Day 54"

echo ""
echo "[ STEP 2: AWS Free Tier - What's Free ]"
echo ""
echo "  12 months free (after account creation):"
echo "  ✅ EC2: 750 hours/month t2.micro or t3.micro"
echo "     (1 instance running 24/7 = free)"
echo "  ✅ S3: 5GB storage, 20,000 GET, 2,000 PUT"
echo "  ✅ RDS: 750 hours db.t2.micro/t3.micro"
echo "  ✅ CloudFront: 1TB data transfer out"
echo "  ✅ Lambda: 1 million requests/month"
echo ""
echo "  Always free (no expiry):"
echo "  ✅ Lambda: 1M requests + 400,000 GB-sec compute"
echo "  ✅ DynamoDB: 25GB storage"
echo "  ✅ CloudWatch: Basic monitoring"
echo "  ✅ SNS: 1M publishes"
echo ""
echo "  ⚠️  IMPORTANT BILLING SAFETY:"
echo "  Set a billing alarm!"
echo "  Billing → Budgets → Create budget"
echo "  Set: \$5 or \$10 monthly threshold"
echo "  Alarm: email you when approaching"
echo "  This prevents accidental charges"

echo ""
echo "[ STEP 3: Enable MFA on Root Account ]"
echo ""
echo "  Root account = master key to everything"
echo "  If compromised: all data, all resources lost"
echo ""
echo "  Enable MFA:"
echo "  AWS Console → Account name → Security credentials"
echo "  → Multi-factor authentication (MFA)"
echo "  → Assign MFA device"
echo "  → Virtual MFA device"
echo "  → Use: Google Authenticator or Authy"
echo ""
echo "  This is MANDATORY, not optional"

echo ""
echo "[ STEP 4: Create Billing Alert ]"
echo ""
echo "  Console → Billing → Budgets → Create budget"
echo "  Choose: Cost budget"
echo "  Amount: \$10 per month"
echo "  Alert: 80% (\$8) → email notification"
echo ""
echo "  Why: mistakes happen (leaving instances running)"
echo "       This catches it before big bills"

echo ""
echo "============================================"
echo "   ACCOUNT SETUP GUIDE COMPLETE"
echo "============================================"
