#!/bin/bash
# ================================================
# 03-aws-services-overview.sh
# AWS Core Services Overview for DevOps
# Author: Asim Raza - Day 53
# ================================================

echo "============================================"
echo "   AWS CORE SERVICES FOR DEVOPS"
echo "   200+ services. These are the essential ones."
echo "============================================"

echo ""
echo "[ COMPUTE ]"
echo "  EC2 (Elastic Compute Cloud) ← Day 56"
echo "    Virtual machines in the cloud"
echo "    Fully configurable (OS, RAM, CPU, storage)"
echo "    You manage: OS, runtime, application"
echo "    Use: web servers, batch processing"
echo ""
echo "  ECS (Elastic Container Service) ← Day 59"
echo "    AWS-managed Docker container service"
echo "    Run your Docker containers"
echo "    Two modes: EC2 (you manage servers)"
echo "               Fargate (AWS manages servers)"
echo ""
echo "  EKS (Elastic Kubernetes Service) ← Day 60"
echo "    AWS-managed Kubernetes"
echo "    Run your K8s workloads on AWS"
echo "    AWS manages: control plane"
echo "    You manage: worker nodes (or use Fargate)"
echo ""
echo "  Lambda ← Day 62"
echo "    Serverless functions"
echo "    Upload code → AWS runs it"
echo "    Pay per request (not per server)"
echo "    Use: event processing, APIs, automation"
echo ""
echo "  Fargate"
echo "    Serverless containers (no EC2 to manage)"
echo "    Works with ECS and EKS"
echo "    AWS manages all the server infrastructure"

echo ""
echo "[ STORAGE ]"
echo "  S3 (Simple Storage Service) ← Day 57"
echo "    Object storage (files, images, backups)"
echo "    Unlimited storage, 99.999999999% durability"
echo "    Use: static websites, backups, artifacts"
echo "    Very cheap (\$0.023/GB/month)"
echo ""
echo "  EBS (Elastic Block Store)"
echo "    Block storage for EC2 (like a hard drive)"
echo "    Attached to one EC2 instance"
echo "    Use: OS storage, databases on EC2"
echo ""
echo "  EFS (Elastic File System)"
echo "    Shared filesystem (multiple instances)"
echo "    Like NFS - many EC2 mount same FS"
echo "    Use: shared config, content storage"
echo ""
echo "  ECR (Elastic Container Registry)"
echo "    Private Docker image registry"
echo "    Like Docker Hub but private + AWS-native"
echo "    Integrates with: ECS, EKS, CodePipeline"

echo ""
echo "[ NETWORKING ]"
echo "  VPC (Virtual Private Cloud) ← Day 55"
echo "    Your private network in AWS"
echo "    Isolated from other customers"
echo "    Contains: subnets, route tables, gateways"
echo ""
echo "  Route53 ← Day 65"
echo "    AWS DNS service"
echo "    Register domains, route traffic"
echo "    Health checks + failover"
echo ""
echo "  CloudFront"
echo "    Content Delivery Network (CDN)"
echo "    Cache content at 400+ edge locations"
echo "    Speeds up: static sites, APIs"
echo ""
echo "  ALB (Application Load Balancer) ← Day 66"
echo "    HTTP/HTTPS load balancer"
echo "    Routes based on URL path/headers"
echo "    Integrates with: ECS, EKS, Auto Scaling"
echo ""
echo "  NLB (Network Load Balancer)"
echo "    TCP/UDP load balancer"
echo "    Extremely high performance"
echo "    Use: millions of requests/second"

echo ""
echo "[ DATABASE ]"
echo "  RDS (Relational Database Service) ← Day 58"
echo "    Managed SQL databases"
echo "    Engines: MySQL, PostgreSQL, Oracle, MSSQL"
echo "    AWS manages: patching, backups, HA"
echo "    You manage: schema, queries, application"
echo ""
echo "  Aurora"
echo "    AWS-optimized MySQL/PostgreSQL"
echo "    5x faster than MySQL, 3x faster than PostgreSQL"
echo "    Auto-scales storage"
echo ""
echo "  DynamoDB"
echo "    Managed NoSQL database"
echo "    Serverless, scales automatically"
echo "    Key-value + document store"
echo "    Use: high-scale, simple lookups"
echo ""
echo "  ElastiCache"
echo "    Managed Redis or Memcached"
echo "    In-memory caching layer"
echo "    Reduces database load"

echo ""
echo "[ SECURITY ]"
echo "  IAM (Identity and Access Management) ← Day 54"
echo "    Who can do what in AWS"
echo "    Users, Groups, Roles, Policies"
echo "    The foundation of AWS security"
echo ""
echo "  KMS (Key Management Service) ← Day 68"
echo "    Encryption key management"
echo "    Encrypts S3, EBS, RDS data"
echo ""
echo "  Secrets Manager"
echo "    Store and rotate secrets"
echo "    Like HashiCorp Vault but AWS-native"
echo "    Automatic rotation for RDS passwords"
echo ""
echo "  WAF (Web Application Firewall)"
echo "    Block SQL injection, XSS, DDoS"
echo "    Protects: CloudFront, ALB, API Gateway"
echo ""
echo "  GuardDuty"
echo "    Threat detection service"
echo "    Analyzes: CloudTrail, VPC Flow Logs, DNS"
echo "    Alerts on: suspicious activity, intrusions"

echo ""
echo "[ DEVOPS / CI/CD ]"
echo "  CodePipeline"
echo "    AWS-native CI/CD pipeline"
echo "    Similar to GitHub Actions but AWS-hosted"
echo ""
echo "  CodeBuild"
echo "    Managed build service"
echo "    Like GitHub Actions runners but managed"
echo ""
echo "  CodeDeploy"
echo "    Automated deployment to EC2, ECS, Lambda"
echo "    Blue-green, canary deployments"
echo ""
echo "  CloudFormation ← Day 61"
echo "    Infrastructure as Code for AWS"
echo "    Define AWS resources in JSON/YAML"
echo "    (Terraform is often preferred - Day 71)"
echo ""
echo "  Systems Manager (SSM)"
echo "    Manage EC2 instances at scale"
echo "    Session Manager: SSH without SSH keys"
echo "    Parameter Store: config and secrets"

echo ""
echo "[ MONITORING ]"
echo "  CloudWatch ← Day 64"
echo "    AWS-native monitoring"
echo "    Metrics, logs, alarms, dashboards"
echo "    Works with ALL AWS services"
echo ""
echo "  CloudTrail"
echo "    Audit log of ALL AWS API calls"
echo "    Who did what, when, from where"
echo "    CRITICAL for security and compliance"
echo ""
echo "  X-Ray"
echo "    Distributed tracing"
echo "    Like Jaeger but AWS-native"
echo "    Debug: which service is slow?"

echo ""
echo "[ SERVERLESS ]"
echo "  Lambda ← Day 62"
echo "  API Gateway ← Day 63"
echo "    HTTP API in front of Lambda"
echo "    REST and WebSocket APIs"
echo "  SQS (Simple Queue Service)"
echo "    Message queue"
echo "    Decouple: producer and consumer"
echo "  SNS (Simple Notification Service)"
echo "    Pub/Sub messaging"
echo "    Fan-out: one message → many subscribers"
echo "  EventBridge"
echo "    Event bus for serverless architectures"

echo ""
echo "[ THE 10 SERVICES EVERY DEVOPS KNOWS ]"
echo "  1.  IAM   - who has access"
echo "  2.  VPC   - your private network"
echo "  3.  EC2   - virtual machines"
echo "  4.  S3    - object storage"
echo "  5.  RDS   - managed database"
echo "  6.  ECS   - containers"
echo "  7.  EKS   - Kubernetes"
echo "  8.  ALB   - load balancing"
echo "  9.  CloudWatch - monitoring"
echo "  10. Route53 - DNS"

echo ""
echo "============================================"
echo "   SERVICES OVERVIEW COMPLETE"
echo "============================================"
