#!/bin/bash
# ================================================
# 04-aws-pricing.sh
# AWS Pricing Model Reference
# Author: Asim Raza - Day 53
# ================================================

echo "============================================"
echo "   AWS PRICING MODEL"
echo "   Understanding how AWS bills you"
echo "============================================"

echo ""
echo "[ PRICING PRINCIPLES ]"
echo ""
echo "  1. Pay for what you use"
echo "     No upfront costs (most services)"
echo "     No termination fees"
echo "     Stop using = stop paying"
echo ""
echo "  2. Pay less when you use more"
echo "     S3: first 50TB cheapest tier"
echo "     Data transfer: first GB most expensive"
echo ""
echo "  3. Pay even less with reservations"
echo "     Reserve capacity 1-3 years = 30-72% discount"

echo ""
echo "[ EC2 PRICING MODELS ]"
echo ""
echo "  On-Demand (default):"
echo "  Pay per hour/second of usage"
echo "  No commitment"
echo "  Most expensive but most flexible"
echo "  Use: unpredictable workloads"
echo ""
echo "  Reserved Instances (1 or 3 year):"
echo "  Commit to a specific instance type"
echo "  Save 30-72% vs On-Demand"
echo "  Use: steady-state production workloads"
echo ""
echo "  Spot Instances:"
echo "  Bid on spare AWS capacity"
echo "  Save up to 90% vs On-Demand"
echo "  Risk: AWS can terminate with 2-min notice"
echo "  Use: batch jobs, data processing, CI/CD runners"
echo ""
echo "  Savings Plans:"
echo "  Commit to dollar amount/hour"
echo "  More flexible than Reserved Instances"
echo "  Save up to 72%"
echo "  Use: when you know you'll spend X/hour"

echo ""
echo "[ COMMON SERVICE COSTS (us-east-1) ]"
echo ""
echo "  EC2:"
echo "  t3.micro:    \$0.0104/hour (~\$7.50/month)"
echo "  t3.small:    \$0.0208/hour (~\$15/month)"
echo "  t3.medium:   \$0.0416/hour (~\$30/month)"
echo "  m5.large:    \$0.096/hour (~\$70/month)"
echo ""
echo "  S3:"
echo "  Storage:     \$0.023/GB/month"
echo "  GET request: \$0.0004 per 1,000"
echo "  PUT request: \$0.005 per 1,000"
echo "  Data out:    \$0.09/GB (first 10TB)"
echo ""
echo "  RDS (MySQL, t3.micro):"
echo "  Single AZ:   \$0.017/hour (~\$12/month)"
echo "  Multi-AZ:    \$0.034/hour (~\$25/month)"
echo ""
echo "  ALB:"
echo "  Fixed cost:  \$0.008/hour (~\$5.84/month)"
echo "  Per LCU:     \$0.008/LCU-hour"
echo ""
echo "  Data Transfer:"
echo "  IN to AWS:   FREE"
echo "  OUT from AWS: \$0.09/GB (first 10TB)"
echo "  Between AZs: \$0.01/GB each direction"
echo "  Same AZ:     FREE"

echo ""
echo "[ DATA TRANSFER GOTCHA ]"
echo "  Data transfer COSTS are often the surprise!"
echo ""
echo "  RDS in us-east-1a"
echo "  App server in us-east-1b"
echo "  Data between them: \$0.01/GB each way"
echo "  10GB queries/day = \$0.10/day = \$3/month"
echo "  (small, but adds up at scale)"
echo ""
echo "  ALWAYS put databases in SAME AZ as app"
echo "  For production: multi-AZ with load balancer"

echo ""
echo "[ AWS COST TOOLS ]"
echo "  Billing Dashboard: current month costs"
echo "  Cost Explorer: historical + forecast"
echo "  Budgets: set alerts when approaching limit"
echo "  Pricing Calculator: estimate before building"
echo "    https://calculator.aws"
echo ""
echo "  AWS Trusted Advisor:"
echo "    Checks: unused resources, overprovisioned"
echo "    Free tier: 5 basic checks"
echo "    Business/Enterprise: all 150+ checks"

echo ""
echo "[ COST OPTIMIZATION TIPS ]"
echo "  1. Delete unused resources (biggest savings)"
echo "  2. Right-size instances (don't over-provision)"
echo "  3. Use Spot instances for non-critical work"
echo "  4. S3 lifecycle policies (move old data to Glacier)"
echo "  5. Reserved instances for stable workloads"
echo "  6. Turn off dev/test environments nights/weekends"
echo "  7. Data transfer: keep traffic within same AZ"
echo "  8. Use CloudFront to cache (reduces origin cost)"

echo ""
echo "============================================"
echo "   PRICING REFERENCE COMPLETE"
echo "============================================"
