#!/bin/bash
# ================================================
# 05-first-cli-commands.sh
# First AWS CLI Commands Reference
# Author: Asim Raza - Day 53
# ================================================

echo "============================================"
echo "   FIRST AWS CLI COMMANDS"
echo "============================================"

echo ""
echo "[ VERIFY CREDENTIALS ]"
echo ""
echo "  aws sts get-caller-identity"
echo "  Output: Account ID, UserID, ARN"
echo "  Shows: which account and user you're using"
echo "  First command to run after aws configure"
echo ""

if command -v aws &>/dev/null; then
    echo "  Running: aws sts get-caller-identity"
    aws sts get-caller-identity \
        --output json 2>/dev/null || \
        echo "  (Configure credentials first: aws configure)"
fi

echo ""
echo "[ REGION COMMANDS ]"
echo ""
echo "  # List all available regions:"
echo "  aws ec2 describe-regions \\"
echo "    --output table"
echo ""
echo "  # List regions in JSON:"
echo "  aws ec2 describe-regions \\"
echo "    --query 'Regions[*].RegionName' \\"
echo "    --output text"
echo ""
echo "  # Check current region:"
echo "  aws configure get region"

echo ""
echo "[ ACCOUNT INFORMATION ]"
echo ""
echo "  # Get account ID:"
echo "  aws sts get-caller-identity --query Account --output text"
echo ""
echo "  # List IAM users (need permissions):"
echo "  aws iam list-users --output table"
echo ""
echo "  # Check your identity:"
echo "  aws sts get-caller-identity"

echo ""
echo "[ EC2 BASIC COMMANDS (preview) ]"
echo ""
echo "  # List running instances:"
echo "  aws ec2 describe-instances \\"
echo "    --query 'Reservations[*].Instances[*].[InstanceId,State.Name,InstanceType,PublicIpAddress]' \\"
echo "    --output table"
echo ""
echo "  # List available AMIs (Amazon Machine Images):"
echo "  aws ec2 describe-images \\"
echo "    --owners amazon \\"
echo "    --filters 'Name=name,Values=amzn2-ami-hvm-2.0.*-x86_64-gp2' \\"
echo "    --query 'Images[0].ImageId' \\"
echo "    --output text"

echo ""
echo "[ S3 BASIC COMMANDS (preview) ]"
echo ""
echo "  # List all buckets:"
echo "  aws s3 ls"
echo ""
echo "  # Create a bucket:"
echo "  aws s3 mb s3://my-unique-bucket-name-2026"
echo ""
echo "  # Upload a file:"
echo "  aws s3 cp myfile.txt s3://my-bucket/"
echo ""
echo "  # List bucket contents:"
echo "  aws s3 ls s3://my-bucket/"
echo ""
echo "  # Download a file:"
echo "  aws s3 cp s3://my-bucket/myfile.txt ."
echo ""
echo "  # Sync directory to S3:"
echo "  aws s3 sync ./dist/ s3://my-bucket/"
echo ""
echo "  # Delete bucket:"
echo "  aws s3 rb s3://my-bucket --force"

echo ""
echo "[ USEFUL CLI FLAGS ]"
echo ""
echo "  --region us-east-1    override default region"
echo "  --profile myprofile   use named profile"
echo "  --output json|text|table|yaml"
echo "  --query 'JMESPath'    filter output"
echo "  --dry-run             validate without executing"
echo "  --no-cli-pager        don't use less/more pager"
echo "  --no-verify-ssl       (not recommended)"
echo ""
echo "  QUERY examples (JMESPath):"
echo "  --query 'Instances[0].InstanceId'"
echo "  --query 'length(Instances)'"
echo "  --query 'Instances[*].[InstanceId,State.Name]'"
echo "  --query 'Instances[?State.Name==\`running\`]'"

echo ""
echo "[ AWS CLI HELP ]"
echo "  aws help                    top-level help"
echo "  aws ec2 help                EC2 service help"
echo "  aws ec2 describe-instances help"
echo "  aws ec2 run-instances help"

echo ""
echo "[ CLI CONFIGURATION FILES ]"
echo ""
echo "  ~/.aws/credentials:"
echo "  [default]"
echo "  aws_access_key_id = AKIAIOSFODNN7EXAMPLE"
echo "  aws_secret_access_key = wJalrXUtnFEMI..."
echo ""
echo "  ~/.aws/config:"
echo "  [default]"
echo "  region = us-east-1"
echo "  output = json"
echo "  cli_pager ="
echo ""
echo "  NEVER commit ~/.aws/ to Git!"
echo "  Add to ~/.gitignore_global:"
echo "  echo '.aws/' >> ~/.gitignore_global"

echo ""
echo "============================================"
echo "   CLI COMMANDS REFERENCE COMPLETE"
echo "============================================"
