#!/bin/bash
# ================================================
# advanced-git-reference.sh
# Advanced Git Commands Reference
# Author: Asim Raza
# Day 22 of DevOps Journey
# ================================================

echo "============================================"
echo "   ADVANCED GIT REFERENCE"
echo "   Author: Asim Raza - Day 22"
echo "============================================"

echo ""
echo "[ GIT REBASE ]"
echo "  git rebase main              = replay commits on main"
echo "  git rebase -i HEAD~3         = interactive last 3 commits"
echo "  git rebase --abort           = cancel rebase"
echo "  git rebase --continue        = continue after conflict"
echo "  git pull --rebase            = pull with rebase"
echo ""
echo "  Interactive rebase commands:"
echo "  pick    = keep commit as is"
echo "  reword  = keep commit, edit message"
echo "  squash  = combine with previous commit"
echo "  fixup   = squash, discard message"
echo "  drop    = remove commit entirely"

echo ""
echo "[ GIT CHERRY-PICK ]"
echo "  git cherry-pick abc1234      = copy specific commit"
echo "  git cherry-pick abc..def     = copy range of commits"
echo "  git cherry-pick --abort      = cancel cherry-pick"
echo "  git cherry-pick --continue   = continue after conflict"

echo ""
echo "[ GIT RESET ]"
echo "  git reset --soft HEAD~1      = undo commit, keep staged"
echo "  git reset HEAD~1             = undo commit, keep files"
echo "  git reset --hard HEAD~1      = undo commit, DELETE all"
echo "  git reset HEAD file.txt      = unstage specific file"
echo ""
echo "  Memory trick:"
echo "  --soft  = go back but keep suitcase packed"
echo "  --mixed = go back and unpack suitcase"
echo "  --hard  = go back and burn the suitcase"

echo ""
echo "[ GIT REVERT ]"
echo "  git revert abc1234           = undo specific commit safely"
echo "  git revert HEAD              = undo last commit"
echo "  git revert HEAD~3..HEAD      = undo last 3 commits"
echo "  git revert --no-commit abc   = revert without committing"

echo ""
echo "[ GIT REFLOG ]"
echo "  git reflog                   = show all HEAD positions"
echo "  git reflog show branch-name  = specific branch history"
echo "  git reset --hard HEAD@{2}    = recover to specific point"
echo "  git checkout -b recovered HASH = recover deleted branch"
echo ""
echo "  Reflog keeps history for 90 days"
echo "  You can ALWAYS recover within 90 days"

echo ""
echo "[ GIT BISECT ]"
echo "  git bisect start             = start binary search"
echo "  git bisect bad               = current is broken"
echo "  git bisect good v1.0.0       = this version was good"
echo "  git bisect good/bad          = after testing each commit"
echo "  git bisect reset             = finish bisect session"
echo "  git bisect run test-script   = automated bisect"

echo ""
echo "[ GIT CLEAN ]"
echo "  git clean -n                 = preview (dry run)"
echo "  git clean -f                 = delete untracked files"
echo "  git clean -fd                = delete files + dirs"
echo "  git clean -fdx               = delete including ignored"
echo "  ALWAYS run -n first!"

echo ""
echo "[ EMERGENCY COMMANDS ]"
echo "  # Committed to wrong branch:"
echo "  git cherry-pick <hash>       = copy to right branch"
echo "  git reset --hard HEAD~1      = remove from wrong branch"
echo ""
echo "  # Accidentally deleted branch:"
echo "  git reflog | grep branch-name"
echo "  git checkout -b branch-name <hash>"
echo ""
echo "  # Pushed wrong code to main:"
echo "  git revert <hash>            = create undo commit"
echo "  git push origin main         = push the revert"
echo ""
echo "  # Hard reset but want code back:"
echo "  git reflog                   = find old hash"
echo "  git reset --hard <old-hash>  = go back to it"
echo ""
echo "  # Committed sensitive data:"
echo "  git reset HEAD~1             = if not pushed"
echo "  # If pushed: rotate credentials immediately!"
echo "  # Use: git filter-branch or BFG Repo Cleaner"

echo ""
echo "============================================"
echo "   REFERENCE COMPLETE"
echo "============================================"
