#!/bin/bash
# ================================================
# swarm-reference.sh
# Docker Swarm Complete Reference
# Author: Asim Raza
# Day 37 of DevOps Journey
# ================================================

echo "============================================"
echo "   DOCKER SWARM REFERENCE"
echo "   Author: Asim Raza - Day 37"
echo "============================================"

echo ""
echo "[ SWARM INITIALIZATION ]"
echo "  docker swarm init --advertise-addr IP"
echo "  docker swarm join --token TOKEN MANAGER:2377"
echo "  docker swarm join-token worker"
echo "  docker swarm join-token manager"
echo "  docker swarm leave --force"

echo ""
echo "[ NODE MANAGEMENT ]"
echo "  docker node ls                    = list nodes"
echo "  docker node inspect NODE          = node details"
echo "  docker node inspect self --pretty = this node"
echo "  docker node promote NODE          = → manager"
echo "  docker node demote NODE           = → worker"
echo "  docker node update --availability drain NODE"
echo "    = stop new tasks, migrate existing"
echo "  docker node update --availability active NODE"
echo "    = re-enable node"

echo ""
echo "[ SERVICE COMMANDS ]"
echo "  docker service create             = create service"
echo "  docker service ls                 = list services"
echo "  docker service ps SERVICE         = list tasks"
echo "  docker service inspect SERVICE    = full details"
echo "  docker service logs SERVICE       = combined logs"
echo "  docker service update             = update service"
echo "  docker service scale S=N          = scale replicas"
echo "  docker service rollback SERVICE   = manual rollback"
echo "  docker service rm SERVICE         = remove service"

echo ""
echo "[ SERVICE CREATE FLAGS ]"
echo "  --name NAME                       = service name"
echo "  --replicas N                      = replica count"
echo "  --publish H:C                     = publish port"
echo "  --network NAME                    = connect network"
echo "  --secret NAME                     = mount secret"
echo "  --constraint 'node.role==worker'  = placement"
echo "  --update-parallelism N            = update batch"
echo "  --update-delay Ns                 = update wait"
echo "  --update-failure-action rollback  = auto rollback"
echo "  --rollback-parallelism N"
echo "  --limit-memory 256M"
echo "  --limit-cpu 0.5"
echo "  --restart-condition on-failure"
echo "  --restart-max-attempts 3"

echo ""
echo "[ ROLLING UPDATES ]"
echo "  docker service update \\"
echo "    --image myapp:v2 myservice"
echo ""
echo "  docker service update \\"
echo "    --update-parallelism 2 \\"
echo "    --update-delay 30s \\"
echo "    --update-failure-action rollback \\"
echo "    --image myapp:v2 myservice"
echo ""
echo "  docker service rollback myservice  = manual rollback"

echo ""
echo "[ SWARM SECRETS ]"
echo "  echo 'value' | docker secret create name -"
echo "  docker secret ls                  = list names only"
echo "  docker secret inspect name        = metadata only"
echo "  docker secret rm name             = delete"
echo "  Accessible in container: /run/secrets/name"

echo ""
echo "[ OVERLAY NETWORKS ]"
echo "  docker network create \\"
echo "    --driver overlay \\"
echo "    --attachable mynet"
echo ""
echo "  Use in service: --network mynet"
echo "  Services use DNS by name (same as bridge)"
echo "  Multi-host: VXLAN tunneling auto"

echo ""
echo "[ STACK DEPLOYMENT ]"
echo "  docker stack deploy -c file.yml NAME"
echo "  docker stack ls                   = list stacks"
echo "  docker stack services NAME        = stack services"
echo "  docker stack ps NAME              = stack tasks"
echo "  docker stack rm NAME              = remove stack"
echo ""
echo "  Stack compose file: add deploy: section"
echo "  deploy:"
echo "    replicas: 3"
echo "    update_config:"
echo "      parallelism: 1"
echo "      delay: 10s"
echo "    resources:"
echo "      limits:"
echo "        memory: 256M"

echo ""
echo "[ PLACEMENT CONSTRAINTS ]"
echo "  node.role == manager"
echo "  node.role == worker"
echo "  node.hostname == server01"
echo "  node.labels.region == us-east"
echo "  engine.labels.storage == ssd"
echo ""
echo "  Add label: docker node update \\"
echo "    --label-add region=us-east NODE"

echo ""
echo "[ SWARM vs SINGLE HOST ]"
echo "  Single host:    docker run / docker compose"
echo "  Swarm:          docker service / docker stack"
echo ""
echo "  Swarm advantages:"
echo "  ✅ Multi-host spreading"
echo "  ✅ Self-healing (restart failed replicas)"
echo "  ✅ Rolling updates"
echo "  ✅ Auto rollback on failure"
echo "  ✅ Routing mesh (any port on any node)"
echo "  ✅ Encrypted overlay networks"
echo "  ✅ Secrets management"

echo ""
echo "[ CURRENT SWARM STATUS ]"
docker info 2>/dev/null | \
    grep -E "Swarm:|NodeID:|Managers:|Nodes:" | \
    sed 's/^/  /'
echo ""
echo "  Services:"
docker service ls 2>/dev/null | sed 's/^/  /' || \
    echo "  No services running"
echo ""
echo "  Nodes:"
docker node ls 2>/dev/null | sed 's/^/  /' || \
    echo "  Swarm not initialized"

echo ""
echo "============================================"
echo "   REFERENCE COMPLETE"
echo "============================================"
