#!/bin/bash
# ================================================
# advanced-actions-reference.sh
# Advanced GitHub Actions Reference
# Author: Asim Raza
# Day 41 of DevOps Journey
# ================================================

echo "============================================"
echo "   ADVANCED GITHUB ACTIONS REFERENCE"
echo "   Author: Asim Raza - Day 41"
echo "============================================"

echo ""
echo "[ REUSABLE WORKFLOWS ]"
echo ""
echo "  Called workflow (06-reusable-called.yml):"
echo "  on:"
echo "    workflow_call:"
echo "      inputs:"
echo "        env:"
echo "          required: true"
echo "          type: string"
echo "      secrets:"
echo "        token:"
echo "          required: true"
echo "      outputs:"
echo "        version:"
echo "          value: \${{ jobs.build.outputs.version }}"
echo ""
echo "  Caller workflow (07-reusable-caller.yml):"
echo "  jobs:"
echo "    my-job:"
echo "      uses: ./.github/workflows/called.yml"
echo "      with:"
echo "        env: staging"
echo "      secrets:"
echo "        token: \${{ secrets.TOKEN }}"

echo ""
echo "[ COMPOSITE ACTIONS ]"
echo ""
echo "  Location: .github/actions/name/action.yml"
echo ""
echo "  action.yml structure:"
echo "  name: 'My Action'"
echo "  inputs:"
echo "    python-version:"
echo "      required: false"
echo "      default: '3.11'"
echo "  outputs:"
echo "    cache-hit:"
echo "      value: \${{ steps.cache.outputs.cache-hit }}"
echo "  runs:"
echo "    using: composite"
echo "    steps:"
echo "      - uses: actions/setup-python@v4"
echo "        with:"
echo "          python-version: \${{ inputs.python-version }}"
echo ""
echo "  Usage in workflow:"
echo "  - uses: ./.github/actions/name"
echo "    with:"
echo "      python-version: '3.11'"

echo ""
echo "[ DEPLOYMENT ENVIRONMENTS ]"
echo ""
echo "  Setup: GitHub → Settings → Environments"
echo ""
echo "  In workflow:"
echo "  jobs:"
echo "    deploy:"
echo "      environment:"
echo "        name: production"
echo "        url: https://app.example.com"
echo ""
echo "  Protection rules:"
echo "  → Required reviewers (approval gate)"
echo "  → Wait timer (delay before deploy)"
echo "  → Deployment branches (only main)"

echo ""
echo "[ DYNAMIC MATRIX ]"
echo ""
echo "  generate-matrix:"
echo "    outputs:"
echo "      matrix: \${{ steps.set.outputs.matrix }}"
echo "    steps:"
echo "      - id: set"
echo "        run: |"
echo "          echo 'matrix={\"python\":[\"3.10\",\"3.11\"]}'"
echo "             >> \$GITHUB_OUTPUT"
echo ""
echo "  use-matrix:"
echo "    needs: generate-matrix"
echo "    strategy:"
echo "      matrix: \${{ fromJSON(needs.generate-matrix.outputs.matrix) }}"

echo ""
echo "[ FAN-OUT / FAN-IN ]"
echo ""
echo "  Fan-out: One job spawns many"
echo "  generate → matrix job A, B, C (parallel)"
echo ""
echo "  Fan-in: Many jobs feed one"
echo "  A, B, C → collect-results"
echo "  needs: [a, b, c]  ← waits for all three"
echo "  if: always()      ← even if some failed"

echo ""
echo "[ SKIP CI ]"
echo ""
echo "  Add to commit message:"
echo "  [skip ci] or [ci skip] or --no-ci"
echo ""
echo "  Detect in workflow:"
echo "  if: !contains(github.event.head_commit.message, '[skip ci]')"

echo ""
echo "[ CONCURRENCY ]"
echo ""
echo "  concurrency:"
echo "    group: \${{ github.workflow }}-\${{ github.ref }}"
echo "    cancel-in-progress: true"
echo ""
echo "  Prevents: old runs finishing after new starts"
echo "  Use: cancel-in-progress: false for production"

echo ""
echo "[ GITHUB_STEP_SUMMARY ]"
echo ""
echo "  Write markdown to:"
echo "  echo '## Title' >> \$GITHUB_STEP_SUMMARY"
echo "  echo '| Col | Col |' >> \$GITHUB_STEP_SUMMARY"
echo "  echo '|-----|-----|' >> \$GITHUB_STEP_SUMMARY"
echo "  echo '| val | val |' >> \$GITHUB_STEP_SUMMARY"
echo ""
echo "  Appears in: Actions → Run → Job Summary tab"

echo ""
echo "[ WORKFLOWS CREATED TODAY ]"
ls ~/DevOps-journey/.github/workflows/0{6,7,8,9,10,11}*.yml \
    2>/dev/null | xargs -I{} basename {}

echo ""
echo "============================================"
echo "   REFERENCE COMPLETE"
echo "============================================"
