#!/bin/bash
# ================================================
# Rolling Update Commands Reference
# Author: Asim Raza - Day 50
# ================================================

echo "============================================"
echo "   ROLLING UPDATE COMMANDS"
echo "============================================"

echo ""
echo "[ DEPLOY / UPDATE ]"
echo "  # Update image (triggers rolling update):"
echo "  kubectl set image deployment/app-rolling \\"
echo "    app=nginx:1.26-alpine"
echo ""
echo "  # Apply updated manifest:"
echo "  kubectl apply -f deployment.yaml"
echo ""
echo "  # With record (for history):"
echo "  kubectl set image deployment/app-rolling \\"
echo "    app=nginx:1.26 \\"
echo "    --record"

echo ""
echo "[ WATCH ROLLOUT PROGRESS ]"
echo "  # Watch status:"
echo "  kubectl rollout status deployment/app-rolling"
echo "  → Waiting for 6 pods to roll out..."
echo "  → deployment.apps/app-rolling successfully rolled out"
echo ""
echo "  # Watch pods:"
echo "  kubectl get pods -l app=demo -w"
echo "  → Shows old pods terminating, new pods starting"
echo ""
echo "  # Describe events:"
echo "  kubectl describe deployment app-rolling"

echo ""
echo "[ ROLLBACK ]"
echo "  # Rollback to previous version:"
echo "  kubectl rollout undo deployment/app-rolling"
echo ""
echo "  # Rollback to specific revision:"
echo "  kubectl rollout undo deployment/app-rolling \\"
echo "    --to-revision=2"
echo ""
echo "  # View rollout history:"
echo "  kubectl rollout history deployment/app-rolling"
echo "  REVISION  CHANGE-CAUSE"
echo "  1         initial deploy"
echo "  2         v2.0.0 - rolling update"
echo "  3         v3.0.0 - feature release"

echo ""
echo "[ PAUSE AND RESUME ]"
echo "  # Pause (freeze mid-update):"
echo "  kubectl rollout pause deployment/app-rolling"
echo ""
echo "  # Resume:"
echo "  kubectl rollout resume deployment/app-rolling"
echo ""
echo "  Use pause to: canary manually"
echo "  Deploy 1 batch → pause → verify → resume"

echo ""
echo "[ SCALING ]"
echo "  # Scale up:"
echo "  kubectl scale deployment/app-rolling --replicas=10"
echo ""
echo "  # Autoscale:"
echo "  kubectl autoscale deployment/app-rolling \\"
echo "    --min=3 --max=10 --cpu-percent=50"

echo ""
echo "============================================"
echo "   COMMANDS REFERENCE COMPLETE"
echo "============================================"
