#!/bin/bash
# ================================================
# 01-security-groups.sh
# Security Groups - Stateful Firewall Reference
# Author: Asim Raza - Day 55
# ================================================

echo "============================================"
echo "   SECURITY GROUPS - STATEFUL FIREWALL"
echo "   Per-instance virtual firewall"
echo "============================================"

echo ""
echo "[ SECURITY GROUPS vs NACLs ]"
echo ""
printf "%-25s %-25s %-25s\n" \
    "Feature" "Security Groups" "NACLs"
printf "%-25s %-25s %-25s\n" \
    "-------" "---------------" "-----"
printf "%-25s %-25s %-25s\n" \
    "Level" "Instance" "Subnet"
printf "%-25s %-25s %-25s\n" \
    "State" "Stateful" "Stateless"
printf "%-25s %-25s %-25s\n" \
    "Rules" "Allow only" "Allow + Deny"
printf "%-25s %-25s %-25s\n" \
    "Return traffic" "Auto-allowed" "Must allow"
printf "%-25s %-25s %-25s\n" \
    "Rule order" "All evaluated" "Numbered order"
printf "%-25s %-25s %-25s\n" \
    "Default inbound" "Deny all" "Allow all"
printf "%-25s %-25s %-25s\n" \
    "Default outbound" "Allow all" "Allow all"

echo ""
echo "[ STATEFUL EXPLAINED ]"
echo ""
echo "  Stateful = connection tracking"
echo "  If you ALLOW inbound port 80:"
echo "  → Response traffic automatically allowed"
echo "  → No outbound rule needed for the response"
echo ""
echo "  Example:"
echo "  Browser → EC2 port 80 (inbound rule: allow)"
echo "  EC2 → Browser port 54321 (auto-allowed, NO rule needed)"
echo ""
echo "  Stateless (NACLs):"
echo "  Must EXPLICITLY allow both directions"
echo "  Inbound HTTP: allow port 80"
echo "  Outbound EPHEMERAL: allow 1024-65535"

echo ""
echo "[ SECURITY GROUP: ALLOW ONLY ]"
echo ""
echo "  Security Groups have NO DENY rules"
echo "  If no rule matches → traffic DENIED"
echo "  (implicit deny — if not allowed, blocked)"
echo ""
echo "  You cannot use SG to block specific IP"
echo "  Use NACL for that"

echo ""
echo "[ PRODUCTION SECURITY GROUP SETUP ]"
echo ""
REGION="${AWS_REGION:-us-east-1}"
APP_NAME="devops-journey"

# ALB Security Group
echo "  ALB Security Group (internet-facing):"
echo "  aws ec2 create-security-group \\"
echo "    --group-name ${APP_NAME}-alb-sg \\"
echo "    --description 'ALB - internet facing' \\"
echo "    --vpc-id vpc-xxx"
echo ""
echo "  Inbound rules:"
echo "  aws ec2 authorize-security-group-ingress \\"
echo "    --group-id sg-ALB-ID \\"
echo "    --protocol tcp --port 80 --cidr 0.0.0.0/0"
echo "  aws ec2 authorize-security-group-ingress \\"
echo "    --group-id sg-ALB-ID \\"
echo "    --protocol tcp --port 443 --cidr 0.0.0.0/0"
echo ""
echo "  ALB SG rules:"
echo "  INBOUND:  80 (HTTP)  from 0.0.0.0/0 (internet)"
echo "  INBOUND:  443 (HTTPS) from 0.0.0.0/0 (internet)"
echo "  OUTBOUND: all (to app servers)"

echo ""
echo "  App Server Security Group:"
echo "  INBOUND:  8000 from ALB-SG (NOT from internet!)"
echo "  OUTBOUND: 3306/5432 to DB-SG (MySQL/PostgreSQL)"
echo "  OUTBOUND: 443 to 0.0.0.0/0 (internet via NAT)"
echo ""
echo "  KEY: reference another SG as source/dest!"
echo "  Instead of: cidr 10.0.0.0/16"
echo "  Use: source sg-ALB-SG-ID"
echo "  Only traffic FROM the ALB is allowed"
echo "  Even if someone gets same-subnet IP, denied"

echo ""
echo "  Database Security Group:"
echo "  INBOUND:  5432 from App-SG (PostgreSQL)"
echo "  OUTBOUND: none needed (stateful)"
echo ""
echo "  Bastion Host Security Group:"
echo "  INBOUND:  22 from YOUR-IP/32 (SSH from office only)"
echo "  OUTBOUND: 22 to App-SG (SSH to private instances)"

echo ""
echo "[ CLI COMMANDS ]"
echo ""
echo "  # Create security group:"
echo "  aws ec2 create-security-group \\"
echo "    --group-name my-sg \\"
echo "    --description 'My SG' \\"
echo "    --vpc-id vpc-xxx"
echo ""
echo "  # Add inbound rule (from CIDR):"
echo "  aws ec2 authorize-security-group-ingress \\"
echo "    --group-id sg-xxx \\"
echo "    --protocol tcp \\"
echo "    --port 80 \\"
echo "    --cidr 0.0.0.0/0"
echo ""
echo "  # Add inbound rule (from another SG):"
echo "  aws ec2 authorize-security-group-ingress \\"
echo "    --group-id sg-APP-ID \\"
echo "    --protocol tcp \\"
echo "    --port 8000 \\"
echo "    --source-group sg-ALB-ID"
echo ""
echo "  # List security groups:"
echo "  aws ec2 describe-security-groups \\"
echo "    --output table"
echo ""
echo "  # Delete security group:"
echo "  aws ec2 delete-security-group --group-id sg-xxx"
echo ""
echo "  # Remove inbound rule:"
echo "  aws ec2 revoke-security-group-ingress \\"
echo "    --group-id sg-xxx \\"
echo "    --protocol tcp --port 80 --cidr 0.0.0.0/0"

echo ""
echo "============================================"
echo "   SECURITY GROUPS COMPLETE"
echo "============================================"
