#!/bin/bash
# ================================================
# 02-nacls.sh
# Network ACLs - Stateless Subnet Firewall
# Author: Asim Raza - Day 55
# ================================================

echo "============================================"
echo "   NETWORK ACLs (NACLs)"
echo "   Stateless subnet-level firewall"
echo "============================================"

echo ""
echo "[ NACL KEY CONCEPTS ]"
echo ""
echo "  NACLs operate at SUBNET level"
echo "  Every subnet has one NACL"
echo "  (Security Groups are per-instance)"
echo ""
echo "  STATELESS: must allow BOTH directions"
echo ""
echo "  Example: web server on port 80"
echo "  NACL INBOUND:  allow TCP port 80 from 0.0.0.0/0"
echo "  NACL OUTBOUND: allow TCP ports 1024-65535 to 0.0.0.0/0"
echo "  (1024-65535 = ephemeral/dynamic ports)"
echo "  (client browser picks random port for its end)"
echo ""
echo "  NUMBERED RULES: processed lowest-first"
echo "  Rule 100: Allow 80 from 0.0.0.0/0"
echo "  Rule 200: Allow 443 from 0.0.0.0/0"
echo "  Rule 300: Deny 22 from 0.0.0.0/0"
echo "  Rule *:   Deny all (implicit)"
echo ""
echo "  First matching rule wins. STOP."
echo "  Order matters! Unlike Security Groups."

echo ""
echo "[ DEFAULT NACL vs CUSTOM NACL ]"
echo ""
echo "  Default NACL (created with VPC):"
echo "  Inbound:  100 Allow All → * Deny All"
echo "  Outbound: 100 Allow All → * Deny All"
echo "  Effectively: allow everything"
echo "  Use: development (permissive)"
echo ""
echo "  Custom NACL (you create):"
echo "  Starts with: deny all (just the * rule)"
echo "  You add allows explicitly"
echo "  Use: production (restrictive)"

echo ""
echo "[ PRODUCTION PUBLIC SUBNET NACL ]"
echo ""
echo "  INBOUND RULES:"
echo "  Rule  100: Allow TCP 80   from 0.0.0.0/0 (HTTP)"
echo "  Rule  110: Allow TCP 443  from 0.0.0.0/0 (HTTPS)"
echo "  Rule  120: Allow TCP 22   from OFFICE-IP (SSH to bastion)"
echo "  Rule  130: Allow TCP 1024-65535 from 0.0.0.0/0 (return traffic)"
echo "  Rule *:   Deny All"
echo ""
echo "  OUTBOUND RULES:"
echo "  Rule  100: Allow TCP 80   to 0.0.0.0/0 (HTTP to internet)"
echo "  Rule  110: Allow TCP 443  to 0.0.0.0/0 (HTTPS to internet)"
echo "  Rule  120: Allow TCP 1024-65535 to 0.0.0.0/0 (return traffic)"
echo "  Rule  130: Allow TCP 8000  to 10.0.0.0/16 (to app layer)"
echo "  Rule *:   Deny All"

echo ""
echo "[ PRODUCTION PRIVATE SUBNET NACL ]"
echo ""
echo "  INBOUND RULES:"
echo "  Rule  100: Allow TCP 8000 from 10.0.0.0/16 (from ALB)"
echo "  Rule  110: Allow TCP 22   from 10.0.1.0/24 (from bastion)"
echo "  Rule  120: Allow TCP 1024-65535 from 0.0.0.0/0 (return from internet)"
echo "  Rule *:   Deny All"
echo ""
echo "  OUTBOUND RULES:"
echo "  Rule  100: Allow TCP 5432 to 10.0.20.0/24 (to DB subnet)"
echo "  Rule  110: Allow TCP 443  to 0.0.0.0/0 (via NAT: package downloads)"
echo "  Rule  120: Allow TCP 1024-65535 to 0.0.0.0/0 (return traffic)"
echo "  Rule *:   Deny All"

echo ""
echo "[ CLI COMMANDS ]"
echo ""
echo "  # Create NACL:"
echo "  aws ec2 create-network-acl \\"
echo "    --vpc-id vpc-xxx \\"
echo "    --tag-specifications 'ResourceType=network-acl,"
echo "      Tags=[{Key=Name,Value=public-subnet-nacl}]'"
echo ""
echo "  # Add inbound ALLOW rule:"
echo "  aws ec2 create-network-acl-entry \\"
echo "    --network-acl-id acl-xxx \\"
echo "    --ingress \\"
echo "    --rule-number 100 \\"
echo "    --protocol tcp \\"
echo "    --port-range From=80,To=80 \\"
echo "    --cidr-block 0.0.0.0/0 \\"
echo "    --rule-action allow"
echo ""
echo "  # Add inbound DENY rule:"
echo "  aws ec2 create-network-acl-entry \\"
echo "    --network-acl-id acl-xxx \\"
echo "    --ingress \\"
echo "    --rule-number 300 \\"
echo "    --protocol tcp \\"
echo "    --port-range From=22,To=22 \\"
echo "    --cidr-block 0.0.0.0/0 \\"
echo "    --rule-action deny"
echo ""
echo "  # Associate NACL with subnet:"
echo "  aws ec2 associate-network-acl \\"
echo "    --network-acl-id acl-xxx \\"
echo "    --subnet-id subnet-xxx"

echo ""
echo "[ WHEN TO USE NACLs vs SGs ]"
echo ""
echo "  NACLs: additional layer, subnet-wide rules"
echo "  Good for: blocking specific IPs (attackers)"
echo "  Good for: compliance (explicit subnet controls)"
echo "  Good for: defense in depth"
echo ""
echo "  Security Groups: primary defense, per-instance"
echo "  Good for: service-to-service control"
echo "  Good for: SG-to-SG references"
echo ""
echo "  Production best practice:"
echo "  BOTH (defense in depth)"
echo "  SG: primary control"
echo "  NACL: backup + block known bad actors"

echo ""
echo "============================================"
echo "   NACLs REFERENCE COMPLETE"
echo "============================================"
