#!/bin/bash
# ================================================
# volumes-reference.sh
# Docker Volumes Complete Reference
# Author: Asim Raza
# Day 29 of DevOps Journey
# ================================================

echo "============================================"
echo "   DOCKER VOLUMES COMPLETE REFERENCE"
echo "   Author: Asim Raza - Day 29"
echo "============================================"

echo ""
echo "[ VOLUME MANAGEMENT COMMANDS ]"
echo "  docker volume create name       = create named volume"
echo "  docker volume ls                = list all volumes"
echo "  docker volume inspect name      = volume details"
echo "  docker volume rm name           = delete volume"
echo "  docker volume prune             = remove unused"

echo ""
echo "[ THREE STORAGE TYPES ]"
echo ""
echo "  1. NAMED VOLUMES (production)"
echo "     -v myvolume:/container/path"
echo "     --mount type=volume,source=myvolume,target=/path"
echo "     Managed by Docker"
echo "     Survives container deletion"
echo "     Best for: databases, persistent data"
echo ""
echo "  2. BIND MOUNTS (development)"
echo "     -v /host/path:/container/path"
echo "     -v /host/path:/container/path:ro  (read-only)"
echo "     --mount type=bind,source=/host,target=/container"
echo "     You control the location"
echo "     Best for: development, config files, SSL certs"
echo ""
echo "  3. TMPFS (security/speed)"
echo "     --tmpfs /container/path:size=100m"
echo "     --mount type=tmpfs,target=/path,tmpfs-size=100m"
echo "     In memory only (never touches disk)"
echo "     Best for: secrets, sensitive temporary data"

echo ""
echo "[ COMMON DATABASE PATTERNS ]"
echo ""
echo "  # PostgreSQL with persistence:"
echo "  docker run -d \\"
echo "    --name postgres \\"
echo "    -e POSTGRES_PASSWORD=secret \\"
echo "    -v postgres-data:/var/lib/postgresql/data \\"
echo "    postgres:15-alpine"
echo ""
echo "  # MySQL with persistence:"
echo "  docker run -d \\"
echo "    --name mysql \\"
echo "    -e MYSQL_ROOT_PASSWORD=secret \\"
echo "    -v mysql-data:/var/lib/mysql \\"
echo "    mysql:8.0"
echo ""
echo "  # Redis with persistence:"
echo "  docker run -d \\"
echo "    --name redis \\"
echo "    -v redis-data:/data \\"
echo "    redis:7-alpine redis-server --appendonly yes"

echo ""
echo "[ BACKUP PATTERN ]"
echo ""
echo "  # Backup volume to tar:"
echo "  docker run --rm \\"
echo "    -v myvolume:/data \\"
echo "    -v \$(pwd):/backup \\"
echo "    ubuntu:22.04 \\"
echo "    tar czf /backup/backup.tar.gz -C /data ."
echo ""
echo "  # Restore from tar:"
echo "  docker run --rm \\"
echo "    -v myvolume:/data \\"
echo "    -v \$(pwd):/backup \\"
echo "    ubuntu:22.04 \\"
echo "    tar xzf /backup/backup.tar.gz -C /data"

echo ""
echo "[ CURRENT VOLUMES ]"
docker volume ls

echo ""
echo "[ VOLUMES DISK USAGE ]"
docker system df | grep "Local Volumes"

echo ""
echo "[ VOLUME LOCATIONS ON HOST ]"
echo "  Named volumes: /var/lib/docker/volumes/"
echo "  Access with:   sudo ls /var/lib/docker/volumes/"

echo ""
echo "[ IMPORTANT REMINDERS ]"
echo "  ✅ Always use volumes for database data"
echo "  ✅ Use :ro for sensitive read-only mounts"
echo "  ✅ Backup volumes before container recreation"
echo "  ❌ Never store important data in container layer"
echo "  ❌ Never commit volume data to Git"
echo "  ❌ Don't mount sensitive host directories"

echo ""
echo "============================================"
echo "   REFERENCE COMPLETE"
echo "============================================"
